### ISSUE TITLE
Arrange button jumps view port when the "List" box on the right sidebar is not on the screen.

### ISSUE THREAD

**Issue by mithriltabby** [worldanvil/worldanvil-bug-tracker#494] opened 2021-08-10 05:31 UTC
**World Anvil Username**: mithriltabby

**World / Campaign / RPG Character / Manuscript Title**: Viridian https://www.worldanvil.com/w/viridian-mithriltabby

**Feature**: Athena

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/world/athena/#

**Describe the Issue**
I decided to test WorldAnvil by entering https://www.mithriltabby.com/viridian/dreaming.html into the lore under Deities & Religions, with one article per major god, plus an introduction. I did quick copy-pastes and instant addition of each article. The articles wound up not in the order in which I entered them, and when I attempted to reorder them with the drag handles:

1. There are two different drag handles, one on the left that looks like a drag handle and one in the middle titled "Arrange". This is redundant and confusing.
2. They have different graphical behaviors
3. When there are too many articles to fit on the screen and a drag begins, the view jumps suddenly, which is very confusing behavior for dragging articles to reorder them.

**To Reproduce**
1. From the Dashboard, go to Article and Categories
2. Click on 'World Encyclopedia'
3. Click on 'Deities & Religions'
4. Add repeated, distinct articles until you exceed the height of your browser window
5. Attempt to reorder them. Note that:
- The viewport jumps when you start to drag
- Dragging to the end of the viewport does not scroll
- The left hand drag icon doesn't work at all
- The Arrange icon does work, but requires multiple moves because the viewport doesn't scroll

**Expected behavior**
1. I expect only one drag handle; the handle on the left clearly indicates that
2. The viewport should not move when drag begins
3. The viewport should scroll when the dragged item reaches the edge

**Screenshots**
Here you can see the articles extending outside the viewport.
![Screenshot from 2021-08-09 22-29-40](https://user-images.githubusercontent.com/89281/128813153-8e04f3ca-fb7b-41d3-a24a-32c9656e8e4b.png)

**Comment by Kordishal** [comment] 2021-08-10 10:43
Hi, 

When creating a new article in Articles & Categories the position weight is unset. This is the reason that they are in random order. This behaviour could be improved by adding a default position either smaller than the lowest or larger than the highest weight within the category.

There are two handles for dragging because they have a different purpose. The Arrange button is to arrange articles within the category. The second button on the left is to drag articles into different categories in the Browse by Categories category tree.

Due to technical limitations and for organizational purposes it is generally not recommended to have more than 20 articles in a single category. This limitation is not enforced, but some features of World Anvil will start to slow down as categories grow larger and work less well.

I can confirm that the arrange button makes the view jump once the "List" box is no longer in the view port and aligns it with that. I do believe that is a bug.

The other behaviour that is a bit irritating is that Browse by Category is collapsed when the arrange button is pressed and then opened when the button is released. I assume this is to make sure people don't try to use the arrange button to try and order in categories, but I feel that is fixed by the arrange button not allowing for horizontal movement. 

It would be useful to have the view port scroll once you reach the edge at the top or at the bottom.

**Comment by Kordishal** [comment] 2021-08-10 11:04
PS: And just to be clear: this recommendation isn't documented anywhere at the moment as far as I know. So I am just letting you know about it :)

**Comment by mithriltabby** [comment] 2021-08-10 18:23
Making the distinct purposes of the two different drag-to-rearrange handles more clear would be worthwhile as well.

**Closed** 2021-08-11 05:45 UTC
Labels: Type: UI / UX, Feature: User Interface

**Comment by iamromeo** [comment] 2021-08-11 05:47
I appreciate the advice but this is not a bug - if you wish to suggest your change, you can use the features request board.
