### ISSUE TITLE
Linear Navigation

### ISSUE THREAD

**Issue by firethorndragon** [worldanvil/worldanvil-bug-tracker#1343] opened 2022-11-05 09:06 UTC
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Firethorndragon

**World / Campaign / RPG Character / Manuscript Title**: Aurin and Reas

**Feature**: 

**Operating System**:

**Browser**: Microsoft Edge 

**Device / Device Model**:

**Related URLS** (To public & visible pages, add screenshots otherwise):

https://www.worldanvil.com/w/aurin-firethorndragon/a/smoke-moss-species-1?preview=true? 
**Describe the Issue**
In all my articles in both my worlds Aurin and Reas all the linear articles I have linked do not work. Instead of the title of the linear articles that I have linked, they instead show numbers and letters instead of the title itself. And when I open the article to edit to see if I've done something wrong, the linear navigation doesn't appear. I have also linked screenshots of the issue as I think it describes it better.

**To Reproduce**

**Expected behavior**
When I open all my articles in view mod, I expect to be able to see all the linear articles I have linked in the past. But now they do not show up instead they do not work at all. And instead of the title of the linear article, it shows up in numbers and letters. I opened edit mode and saw that the Linear Navigation section was gone. It is not there at all. And I expected to see it there like I always do when I edit my articles. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Skärmbild 2022-11-05 094556](https://user-images.githubusercontent.com/83641590/200112167-ecf7b728-9915-436a-8255-9abc1a25574e.png)
![Skärmbild 2022-11-05 094637](https://user-images.githubusercontent.com/83641590/200112170-e6c658fe-c302-4711-a453-e9ce90c11287.png)

**Comment by iamromeo** [comment] 2022-11-05 09:51
Please do not open new issues when there is an issue already raised 

duplicate of: #1336

**Closed by iamromeo** 2022-11-05 09:51 UTC
