### ISSUE TITLE
Heroes Character Profile image is added to oldest character gallery when added during character creation

### ISSUE THREAD

**Issue by artyrambles** [worldanvil/worldanvil-bug-tracker#129] opened 2021-04-05 19:17 UTC
**World Anvil Username**: arty

**Feature**: Heroes Character Galleries

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/hero/concord-official (go to gallery tab)

**Describe the Issue**
When I upload an image to any of my Heroes character's (for their profile image), the images show up in the wrong character's gallery.

**To Reproduce**
1. Have character A
2. Create new character B
3. Give the character B a profile image
4. Image will show up in character A's gallery

**Expected behavior**
The images should show up in the respective character's gallery.

**Screenshots**
![character A gallery](https://user-images.githubusercontent.com/29456646/113615233-e5fdce80-9653-11eb-9656-31119a1c39dd.JPG)

**Comment by Kordishal** [comment] 2021-04-06 07:49
![image](https://user-images.githubusercontent.com/14262536/113676931-4d9c3400-96bd-11eb-8e52-1564f0d9c76d.png)

Every time a protrait is added to character it is added to its gallery. They are not removed when adding a new image. But they can be removed manually.

So I think this is working as intended?

**Comment by iamromeo** [comment] 2021-04-06 08:13
That is working as intended unless there was something different @artyrambles meant. I thought he said that the portrait was added to another character and also to that?

**Comment by iamromeo** [comment] 2021-04-06 08:13
Also, nice portraits @Kordishal

**Comment by artyrambles** [comment] 2021-04-06 08:14
Yeah the images are added to a different character's gallery.

**Comment by Kordishal** [comment] 2021-04-06 17:52
@iamromeo We found the issue. 

When creating a new character and adding an profile picture in the New Character form it is added to the gallery of the oldest character on the account instead of the character created.

The issue can be resolved by deleting the image from the gallery and re-uploading

**Comment by iamromeo** [comment] 2021-04-10 06:23
Still cannot replicate this.

**Comment by iamromeo** [comment] 2021-04-23 07:06
Reproduced. Fixing

**Closed** 2021-04-23 07:11 UTC
Labels: Feature: RPG Characters, Priority: Optional, Severity: Minor, Type: Bug
