### ISSUE TITLE
Dashboard category duplication

### ISSUE THREAD

**Issue by PleasantPheasant77** [worldanvil/worldanvil-bug-tracker#1069] opened 2022-06-06 13:26 UTC
PleasantPheasant77:

Dime-a-Dozen Dimensions:

Dashboard: 

![image](https://user-images.githubusercontent.com/106975794/172169009-2ea606a2-18ba-4976-ade3-3ec2542378b1.png)
:

Clicking too fast opens categories multiple times, clogging up the screen

**To Reproduce**
1. Go to dashboard
2. Click on any category quickly
3. See error

**Expected behavior**
I expected the category to open once, using a trackpad makes accidental rapid clicking inevitable
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment] 2022-06-06 13:31
This issue will not be addressed at this time. Its not too hard to avoid and can be resolved by reloading the page.

Duplicate of #221

**Closed by Kordishal** 2022-06-06 13:31 UTC
Labels: Status: Will Not Fix, Type: UI / UX, Feature: User Interface
