### ISSUE TITLE
Manuscript Issue

### ISSUE THREAD

**Issue by sulphurman337** [worldanvil/worldanvil-bug-tracker#579] opened 2021-09-21 13:25 UTC
**World Anvil Username**:
Shadeauxrin
**World / Campaign / RPG Character / Manuscript Title**:
Manuscript deletion
**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

When trying to delete manuscript I press delete manuscript. I type in the title to confirm it's to be deleted. I confirm and click ok. It changes the page to a page with 404 you have reached the edge of this world. I go back to home page and the manuscript is still there.

**To Reproduce**

**Expected behavior**

I'm assuming the manuscript that's meant to be deleted shouldn't appear in the list any longer.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment] 2021-09-21 16:17
Hey there @sulphurman337 
please make sure you check/search the list of bugs before you report one :) 
This is a duplicate of https://github.com/worldanvil/worldanvil-bug-tracker/issues/206

**Closed by iamromeo** 2021-09-21 16:17 UTC

**Comment by Kordishal** [comment] 2021-09-21 19:09
duplicate of #206
