### ISSUE TITLE
Unable to access world

### ISSUE THREAD

**Issue by WickDM88** [worldanvil/worldanvil-bug-tracker#521] opened 2021-08-23 11:05 UTC
**World Anvil Username**: Wick88

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/world/18935153-9a96-4556-8bcc-f762b2f68889/summary

**Feature**: Accessing account

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
Get directed to Hobbits error message when trying to access world

**To Reproduce**
1. Go to 'world dashboard'
2. See error

**Expected behavior**
To be able to access the worlds settings and articles

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/89390438/130437250-e98f5e3c-c429-4c2e-ba70-66fab107cc50.png)
![image](https://user-images.githubusercontent.com/89390438/130437314-b13ffbd7-8dd0-4ea7-8497-faa12cd6948b.png)

**Comment by iamromeo** [comment] 2021-08-24 03:21
This is not a bug - this world is locked - the chances are that this is a private world and you no longer have an active subscription is this the case?

**Comment by WickDM88** [comment] 2021-08-24 08:02
I have an active sub currently yes. It's due to cancel though as I can't
access the world, I tried reaching out on discord and was told to log it as
a bug, I took a back up of my world and cancelled my subscription - I've
paid £132 so far, can't afford to keep paying £11 a month for something I
can't currently use!

**Comment by Kordishal** [comment] 2021-08-24 08:19
Ah sorry, I intended to add some more context:

I can confirm that they have an active Grandmaster subscription. They absolutely should still have access to the world as is. 

Profile: https://www.worldanvil.com/author/Wick88

They cancelled the subscription in response to the fact that they are no longer able to access the world. So the question is why was the world locked in the first place? It should not be.

Co-owners and editors can no longer access it as well (2 confirmed).

I had them report this here, because they can still access their other worlds and there was no message that they were blocked for a ToS violation.

**Comment by iamromeo** [comment] 2021-08-24 11:30
@WickDM88 @Kordishal Which world are you trying to access? 
I can see 4 worlds in total 
3 public 
1 archived (with the same name with the one of the active ones)

**Comment by WickDM88** [comment] 2021-08-24 13:05
Hi,

I'm trying to access the Adventure Capitalists world -
https://www.worldanvil.com/world/18935153-9a96-4556-8bcc-f762b2f68889/summary

Cheers,

Willis Hall

**Comment by Kordishal** [comment] 2021-08-24 13:36
Hi,

That link does not work for anyone but you, co-owners and editors. Have you tried to follow the steps Dimitris has outlined exactly? If you are not sure, please message me (SoulLink) on Discord. We've talked there before.

**Comment by iamromeo** [comment] 2021-08-24 13:55
I am really sorry but if the instructions I am giving in order to resolve an issue are not followed I cannot help with resolving that issue. 

@Kordishal I am closing this issue - Feel free to reopen it if there is any actual actionable information

**Comment by iamromeo** [comment] 2021-08-24 14:17
This world has 13 co-authors. 
Your account has access to 9
That can mean only two things. 
1. You have tried to cheat the system (possibly with multiple pages open on the Access page) 
2. This world was moved by a Sage account to you or you used to have a Sage account (which I cannot see a record of) 

Can you please let me know which of those is the case?

**Comment by WickDM88** [comment] 2021-08-24 14:38
The additional co-authors were pre agreed, as per the following:

![image](https://user-images.githubusercontent.com/89390438/130636613-17943c5d-15cb-4d06-9fa9-3cc286b7c84a.png)

**Comment by iamromeo** [comment] 2021-08-24 14:39
Have you upgraded during times?

**Closed** 2021-08-24 14:49 UTC
Labels: Type: Bug, Feature: World
