### ISSUE TITLE
Root level element in manuscript is not displayed

### ISSUE THREAD

**Issue by cedorsett1334** [worldanvil/worldanvil-bug-tracker#839] opened 2022-01-25 19:36 UTC
**World Anvil Username**: 

cedorsett

**World / Campaign / RPG Character / Manuscript Title**: 

Barren's End

**Feature**: 

Manuscript

**Related URLS** (To public & visible pages add screenshots otherwise):

https://www.worldanvil.com/community/manuscripts/read/9490137820-cedorsett-shatter-me3A-dance-the-ghost-book-1

**Describe the Issue**

I went in to add more chapters to the story and the manuscript setting are missing. The published chapters are not showing up and when I tried to delete it to start again, I recieved a 404 error.

**To Reproduce**
I opened the manuscript.

**Expected behavior**

I should have been able to edit the settings or delete the manuscript.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

<img width="798" alt="screenshot" src="https://user-images.githubusercontent.com/88609720/151046969-825ffada-1a19-4946-9652-58915636fec6.png">

**Comment by iamromeo** [comment] 2022-02-03 07:41
Hey there @cedorsett1334 I am a bit confused. Looking at your sidebar it looks like there is no parent for those chapters. 
There must be an actual top level entity there 

![image](https://user-images.githubusercontent.com/660175/152301025-2155f328-6ebb-4772-9e68-188d8d9dd1ba.png)

**Comment by iamromeo** [comment] 2022-02-10 10:21
No reply for oever 1 week

**Comment by cedorsett1334** [comment] 2022-02-10 15:16
Sorry, I never saw the previous email, and this answer will probably not go
through, but you identified the problem. The root options are missing on
this document, and it just needs to be deleted.
-- 
Charlie Dorsett
----------------------------------------
Website: http://www.projectshadow.com
Twitter/Instagram: cedorsett

**Comment by Kordishal** [comment] 2022-02-10 16:22
It probably means the root element was somehow deleted, but the rest of the Manuscript still somehow exists.

**Comment by iamromeo** [comment] 2022-02-10 21:28
This is no longer related to this issue.

**Comment by iamromeo** [comment] 2022-02-10 21:28
Duplicate of https://github.com/worldanvil/worldanvil-bug-tracker/issues/206

**Closed** 2022-02-10 21:28 UTC
Labels: Type: Bug, Feature: Manuscripts
