### ISSUE TITLE
Blocking -- Cannot Leave Legacy Editor

### ISSUE THREAD

**Issue by Ademal** [worldanvil/worldanvil-bug-tracker#275] opened 2021-05-20 23:57 UTC
**User**: Ademal

**Feature**: Editor

**Describe the Issue**
If you set your editor to Legacy and attempt to change it back, you get a 404. 

This is personally blocking because my BBCode breaks in the Legacy editor and is converted to HTML.

Found while helping @Shikya Karaskage#1337, who reported they were stuck on the Legacy Editor. In recreating it, I got the same issue.

**Comment by Kordishal** [comment] 2021-05-21 04:09
Duplicate of #270

**Closed by Kordishal** 2021-05-21 04:09 UTC
Labels: Feature: Account & Profile, Type: Duplicate
