### ISSUE TITLE
Whiteboards

### ISSUE THREAD

**Issue by BasicRin** [worldanvil/worldanvil-bug-tracker#1177] opened 2022-07-22 04:01 UTC
**World Anvil Username**:
BasicDragon
**World / Campaign / RPG Character / Manuscript Title**:
All of my worlds
**Feature**: 
Whiteboards
**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
New whiteboards don't load.

**To Reproduce**
1. I click on the create whiteboard button
2. I arrive at the whiteboard page
3. The whiteboard disappears after a second and I only see a blank page.

**Expected behavior**
I am expecting the new whiteboard to open.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![whiteboards](https://user-images.githubusercontent.com/46877174/180359732-84d00efe-745d-4d9e-9973-4bb7223e1f72.gif)

**Comment by iamromeo** [comment] 2022-07-22 16:22
Duplicate of #1176

**Closed by iamromeo** 2022-07-22 16:22 UTC
