### ISSUE TITLE
Article has no URL slug

### ISSUE THREAD

**Issue by carterartist** [worldanvil/worldanvil-bug-tracker#934] opened 2022-03-20 03:56 UTC
**World Anvil Username**: id8tionist

**World / Campaign / RPG Character / Manuscript Title**: Dierde

**Feature**: people linking

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/dierde-id8tionist/a/session-143A-mindflayer-colonies-26-wizard-hideouts-report-report?preview=true

**Describe the Issue**
A clear and concise description of what the issue is. I have a character, Vyerith, who is tagged and I can't find the page for her. Whenever I put the @vyerith tag on the page it makes a "person" link which returns to the same page it is supposed to leave.

**To Reproduce**
1. Go to '...' https://www.worldanvil.com/w/dierde-id8tionist/a/session-143A-mindflayer-colonies-26-wizard-hideouts-report-report?preview=true or https://www.worldanvil.com/w/dierde-id8tionist/a/the-secrets-of-the-rainforest-plot?preview=true
2. Click on '....' Vyerith

**Expected behavior**
A clear and concise description of what you expected to happen. It should go to the "Vyerith" page which also does NOT show up in the search.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment] 2022-03-20 04:17
Hey @carterartist I have went through the page and **Vyerith** does not present as a link to me at any point. 
That most probably means that the article is a **draft** and/or **private** - do you have a link for Vyerith as an article?


In other news: WOW that is some amazing work you have been doing there - this is quite amazing.

**Comment by Kordishal** [comment] 2022-03-20 10:03
![image](https://user-images.githubusercontent.com/14262536/159157256-2fad1c8b-39a9-430f-9724-d85d422f929b.png)

The link is under this section and it is wired up with the article itself. However, the IDs of this article and of the link are different, so its unclear why this would be.
![image](https://user-images.githubusercontent.com/14262536/159157343-52af9148-939e-42b3-af34-0530e3223b49.png)

**Comment by iamromeo** [comment] 2022-03-21 04:55
I need to see the actual code that generates this. 
![image](https://user-images.githubusercontent.com/660175/159206987-ed36d182-93a1-4502-bcc6-bb54f9ea6520.png)

**_Debug notes_**
article id: **81a92c0d-08bb-4822-b4cf-8afae1773923**

![image](https://user-images.githubusercontent.com/660175/159207241-8e2547ee-3b68-4c26-80ae-8e24ca6db901.png)

The article has no **slug** (browser url) I cannot imagine how this could happen. Did you use a custom URL?

**Comment by Kordishal** [comment] 2022-03-21 07:36
@ Dimitris: The no slug issues happens occasionally. It is fixed by re saving the title of the article. I've never had anyone report it, because its impossible to reproduce and it has never happened to me.

**Comment by iamromeo** [comment] 2022-03-21 09:30
In which case the solution is simple - reenter the title of the article :)

**Closed by iamromeo** 2022-03-21 09:30 UTC
Labels: Type: Bug, Feature: Articles & Templates
