### ISSUE TITLE
All prose articles return an internal server error when trying to view them.

### ISSUE THREAD

**Issue by Jacob-W5570** [worldanvil/worldanvil-bug-tracker#1372] opened 2022-11-29 11:00 UTC
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:
Jacob-W
**World / Campaign / RPG Character / Manuscript Title**:
Red Sunrise
**Feature**: 
Prose articles
**Operating System**:
Windows
**Browser**:
Chrome

**Related URLS** (To public & visible pages, add screenshots otherwise):
https://www.worldanvil.com/w/red-sunrise-jacob-w
**Describe the Issue**
I can't open my prose articles, not from the world view. like any visitor.
nor from the edit side via the dashboard. 

**Screenshots**
![image](https://user-images.githubusercontent.com/82756622/204512017-6c2e4f32-44b5-4219-b027-b132a40fe6ad.png)
If I click any of the articles in the Category Season 1, the season 1 stays up and nothing changes.

**Comment by iamromeo** [comment] 2022-11-29 13:18
Although  I can see it happening on your world I cannot reproduce it on any other environment.

**Comment by Jacob-W5570** [comment] 2022-11-29 13:40
Ah, I think I maybe found the fault. the bbcode [userstate]  is not working right or, more likely, I used it wrong. 

I had this:
[userstate:loggedout]I'm sorry but you need to log in to World Anvil to read this article.[/userstate]
[userstate:notfollower]I'm sorry but you have to be a follower of Red Sunrise to read this article.[follow:0b5e1a8b-8a7e-4b00-b302-d767a4f396d4[/userstate]
[userstate:follower]
TEXT
TEXT 
TEXT
[/userstate]

But I'm fairly sure that it worked as I was expecting it to when I set it up the first time.

I've removed it from this one: 
https://www.worldanvil.com/w/red-sunrise-jacob-w/a/ii-always-summer-prose
but not yet from the others, in case you want to do any more investigation

**Comment by Kordishal** [comment] 2022-11-29 13:52
The offending code that causes the renderer to break is: `[follow:0b5e1a8b-8a7e-4b00-b302-d767a4f396d4[/userstate]`

It is missing the closing bracket on the follow BBCode, but without another BBCode directly behind it it does not break and instead just print the code itself.

So just adding `[follow:0b5e1a8b-8a7e-4b00-b302-d767a4f396d4` is not a problem.

**Closed** 2022-11-29 16:50 UTC
Labels: Type: Bug, Feature: Articles & Templates
