### ISSUE TITLE
Cannot save NPC Extended profile

### ISSUE THREAD

**Issue by Nagdalam** [worldanvil/worldanvil-bug-tracker#1144] opened 2022-07-06 12:32 UTC
**El Mapache**:

**Humidia/Humidia Campaign**:

**Cannot save Extended Npcs Profile - Error 404**: 

**[Related URLS** (To public & visible pages add screenshots otherwise):](https://www.worldanvil.com/heroes/campaign/npc/f6110439-d2db-413d-a569-a7c4679b9b24/extended)

**Describe the Issue**
When trying to save a NPC Extended Profile, I'm constantly taken to an error 404 page.

**To Reproduce**
1. Go to Campaign
2. Go to the NPC Tab
3. Click on any NPC
4. Click on Extended NPC Profile
5. Scroll down to Save Changes
6. You'll be taken to an "Error 404" page and the page will not be saved

**Expected behavior**
I expected my NPC profile to be simply saved.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![World anvil bug](https://user-images.githubusercontent.com/54810519/177550620-1b4e4b27-2876-487e-b414-9d0b51e9f12b.png)
![World anvil bug 2](https://user-images.githubusercontent.com/54810519/177550624-bfc110e2-3257-44e5-8db9-d368f08ad0ca.png)

**Comment by Kordishal** [comment] 2022-07-06 12:54
Duplicate of #1136

**Closed by Kordishal** 2022-07-06 12:54 UTC
