### ISSUE TITLE
Missing plot information

### ISSUE THREAD

**Issue by DBZeke5** [worldanvil/worldanvil-bug-tracker#1403] opened 2023-01-06 03:48 UTC
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**:DBZeke

**World / Campaign / RPG Character / Manuscript Title**:Tartys/ Mutant Mayhem

**Feature**: 

**Operating System**: Windows

**Browser**: Firefox

**Device / Device Model**: Custom Desktop

**Related URLS** (To public & visible pages, add screenshots otherwise):https://www.worldanvil.com/world/plot/894efca7-8086-46f1-b122-ff6711832619/edit
https://www.worldanvil.com/w/tartys-dbzeke/a/mutant-mayhem--plot

**Describe the Issue**
When I go to view this plot in the world view nothing but the title appears.

**To Reproduce**
1. Go to 'https://www.worldanvil.com/w/tartys-dbzeke/a/mutant-mayhem--plot'
2. See error

**Expected behavior**
All the information that is found at the below URL.
https://www.worldanvil.com/world/plot/894efca7-8086-46f1-b122-ff6711832619/edit

**Screenshots**
![image](https://user-images.githubusercontent.com/122071671/210926094-aae0a7e5-a519-4548-9786-976c25cd0f3b.png)

**Comment by Kordishal** [comment] 2023-01-06 06:06
Hi, the article is private and we would need a screenshot of the text you put into the article. Otherwise we will not be able to determine what is going on here. It could be an issue caused by some kind of CSS class or by a BBCode tag that is not properly opened or closed.

**Comment by DBZeke5** [comment] 2023-01-15 21:07
Hello Jonas, sorry for the delay in response, I’ve made the article public.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Kordishal** [comment] 2023-01-15 21:31
Hi, you also need to publish the article for me to take a look. And can you show me the text you wrote in the editor?

**Comment by DBZeke5** [comment] 2023-01-15 21:35
Done and done.
Mutant Mayhem
Main Adversary type
Villain
________________________________
________________________________
Act I
Intro Goal
Stop whoever is poisoning the Swamp Swamp.
Intro Situation
During the evening of the second night of Wintercrest, a parade commences with floats, performers, and musicians. With throngs of people surrounding the street to watch, the party finds itself tightly packed in the crowd. Many guards overwatch the festivities, the Shadowmasters of Soto<https://www.worldanvil.com/w/tartys-dbzeke/a/shadowmasters-of-soto-organization?preview=true> <https://www.worldanvil.com/world/organization/2dc0b626-3ed3-4495-947e-5ea16d9e9261/edit> strategically take out crossbowmen and impersonate the guards until they receive the signal to attack. Their target is the dean of Glassbow college.
You hear the rattling of numerous drums accompanied by the toots of horns coming from down the street. Performers of all sorts start of the parade, from jugglers to fire eaters a wide gambit of performers adorns the street. Along with the performers, elegant coaches being pulled by various beasts come into sight. You watch as businesses and guilds promote their themselves, partially though you notice a float with the decapitated head of a creature. Though the creature's bulbous orb-like eyes and pale green skin is attention-grabbing, those who stand atop the float waving to the crowd catches your attention more. Roland and the shallow chains wave to the crowd displaying their kill and promoting the Huller Guild<https://www.worldanvil.com/w/tartys-dbzeke/a/huller-guild-organization?preview=true><https://www.worldanvil.com/world/organization/bd6e0317-a2cd-4245-a8f6-ff4c9c21600a/edit>
. They don't seem to notice you in the thoroughfare.
*Khipella* You notice Roland stop waving for a second and glance in your direction. You hear the voice of Roland in your head "well I'm glad to see you're still alive"
And soon they're out of sight, leaving more elaborate floats before you. One in particular that has gained a lot of attention is one made of large clockwork. Huge gold and silver gears interlock rotating together propelling the float forward. Atop the float, you see an old human man with a large white beard and kind green eyes.
*perception check DC 17 notices a figure up front brandishing a weapon and moving towards the float, DC 20 notices a guard posted on the rooftop is pointing a crossbow at the old man, DC 20+ notices four others among the crowd and rooftops that appear to be preparing to attack.
________________________________
Act II
Set-up Journey
Option 1: The party is summoned to the college by Chair Glassbow<https://www.worldanvil.com/w/tartys-dbzeke/a/chair-glassbow-person?preview=true> <https://www.worldanvil.com/world/person/cb2ebd27-fd21-4d03-8d7e-4da84b5f5052/edit> . Option 2: Roland seeks out the party and offers them the job that Chair has put out. 1: You see a young student wearing their academic attire with a letter in hand enter the tavern. They have an air of uncertainty and an expression as though they are looking for something.*if not addressed they speak with the tavern keep and approach the party. The young boy hands the party Letter from Chair Glassbow<https://www.worldanvil.com/w/tartys-dbzeke/a/letter-from-chair-glassbow-document?preview=true> <https://www.worldanvil.com/world/document/32ab3744-e3d7-4c15-86d8-b4c3259bb742/edit> . 2: While eating breakfast Khipella feels something tug at her boot. Looking down a brown and cream-colored ferret seems to be trying to get her attention, it will then climb up her leg and onto the table. Sitting up it looks into her eyes and gives this message "Khipella my dear I have a job opportunity that I think fits you and your partner's skill sets splendidly. Come to Huller Hall. Roland."
*When the party enters the meeting hall they see Roland seated with his companion Norf Gilpin* Roland waves you over and gestures you to sit, once you get close the dragon-born whispers something in Roland's eye and leaves the table. "Well, I'm glad you received Thulder's ferret. I was worried the bedraggled little thing wouldn't find you. I'm glad to see your well, its been awhile since we parted ways in Fafall, how has your travels faired you?


  *   The job was posted just after the attack during the parade, the dear dean seems to be wanting experienced investigators that are unknown in the area. I thought you fit the bill nicely. Pay isn't bad either 21,637gp
  *   Well, there isn't any detail on what he wants, happens from time to time. I suppose hes suspicious of who wanted him dead. He asks also that those chosen come dressed as commoners.
  *   I haven't had much dealings with the college, I've met the dean a hand full of times over the years. He's amicable enough.
  *   Ah ah don't forget your seal of approval, without this you won't have the guild's backing.

Arriving at the college the party is led up high into the granite tower. Copper pipes and tanks are affixed to the outer sides of the structure, and grey steam puffs out of various valves. The hot humid temperature of the stairway is a stark contrast to the frigid winter air. You notice that the more stairs you climb the louder a ticking of a distance clock becomes. Upon reaching the door you see the attendant stop and wait for everyone to catch up, upon the last of your arrival he pulls a knob on the side of the door and you hear from behind the door the soft melody of bells. Moments later a short rotund metal creature is before you in the doorway.

Hawkins:
  *
     *   "May I help you?"
     *   "You wouldn't understand my name, but Master Chair has dubbed me Hawkins so you may address me as such"
     *   "I'm from the great plane of order Mechanus, keeper of time, and creation of the all-powerful Primus.""I'm from the great plane of order Mechanus, keeper of time, and creation of the all-powerful Primus."

The room you step into is a mess of papers, vials, gears, and every manner of book. The older gentleman that you had seen atop the float looks up from some notebook.
Chair:

  *   "You must be from the Huller guild, wait you were the same ones from the parade?! Well, this is serendipitous. Tell me what're your names?"
  *   "How familiar are you with the recent years of Totharal?"
  *   "Though I haven't been about to find any evidence I believe that my former mentor had an accomplice. His pupil is still conducting these mutants. This is where you come into the picture, If I'm caught snooping around it could prove fatal to the investigation. Also, I'm not inclined to die just yet, I'm much too busy."
  *   There is the Wintercrest Mascrade tomorrow night and it would be the perfect chance for you to scrutinize the staff. I'll arrange for you to be in attendance, But I warn you that your and I's involvement shouldn't be unknown. If the wrong ears found out about you being hired, renegade wererats wouldn't be our only issue.

With the rising tension between the lower class and the nobility of Totharal<https://www.worldanvil.com/w/tartys-dbzeke/a/totharal-settlement?preview=true> <https://www.worldanvil.com/world/settlement/3c922acd-b2de-48f1-aea5-961280e93a2c/edit> gangs formed to exact their view of justice. One such gang was the Shadowmasters of Soto<https://www.worldanvil.com/w/tartys-dbzeke/a/shadowmasters-of-soto-organization?preview=true> <https://www.worldanvil.com/world/organization/2dc0b626-3ed3-4495-947e-5ea16d9e9261/edit> , these secretive criminals are skilled thieves and anarchists. Their presence in Totharal has led to preemptive measures from the governor Colas Godart<https://www.worldanvil.com/w/tartys-dbzeke/a/colas-godart-person?preview=true> <https://www.worldanvil.com/world/person/8dbe4d4b-dc9f-4328-9444-e6a85ab0e900/edit> to institute more guards and stricter rule. This has only fueled the dissatisfaction of the lower classes with the nobles. Members of the Glassbow College<https://www.worldanvil.com/w/tartys-dbzeke/a/glassbow-college-organization?preview=true> <https://www.worldanvil.com/world/organization/b5766a4b-30e0-4ce7-8a60-0d4763cafbea/edit> have poured more fuel on the growing conflict. Olin Whitlock<https://www.worldanvil.com/w/tartys-dbzeke/a/olin-whitlock-person?preview=true> <https://www.worldanvil.com/world/person/f00b312f-cefb-4bed-82ec-6bc22ed0c5c5/edit> an instructor at the college has played a twisted role, arranging the abduction of a multitude of peasants to conduction experiments on. He desired to mutate humans to become a stronger and more dominating race, most of his subjects didn't survive so he would dump the corpses down the river. But eventually, his dark secret was found out by Chair Glassbow<https://www.worldanvil.com/w/tartys-dbzeke/a/chair-glassbow-person?preview=true> <https://www.worldanvil.com/world/person/cb2ebd27-fd21-4d03-8d7e-4da84b5f5052/edit> , the dean of the college and former pupil of Olin. Chair alerted the governor of Olin's dark deals and arrange for his arrest. When the guards confronted the mage, a massive chemical explosion set the laboratory ablaze. The burnt left hand of Olin was all that was found of his body. Investigations into his search were conducted best that could be down, but the fire left few trails. When word of the atrocities committed by the nobility got to the lower classes, they were enraged. Louis Soto<https://www.worldanvil.com/w/tartys-dbzeke/a/louis-soto-person?preview=true> <https://www.worldanvil.com/world/person/847e13a2-c1d8-4f60-8c4c-6dd768106728/edit> fanned that anger to revolt against the government, he watched on as the peasantry were massacred at the gates of the governor hall. Though the guards were defending the hall it was viewed by many as a war between the classes. Soto was one of them.
Related Characters

  *   <https://www.worldanvil.com/world/person/cb2ebd27-fd21-4d03-8d7e-4da84b5f5052/edit> Chair Glassbow<https://www.worldanvil.com/w/tartys-dbzeke/a/chair-glassbow-person>
  *   <https://www.worldanvil.com/world/person/8dbe4d4b-dc9f-4328-9444-e6a85ab0e900/edit> Colas Godart<https://www.worldanvil.com/w/tartys-dbzeke/a/colas-godart-person>
  *   <https://www.worldanvil.com/world/person/f00b312f-cefb-4bed-82ec-6bc22ed0c5c5/edit> Olin Whitlock<https://www.worldanvil.com/w/tartys-dbzeke/a/olin-whitlock-person>

Related Organizations

  *   <https://www.worldanvil.com/world/organization/74aa5484-f8af-45b9-b75a-214f2016b39b/edit> Bahlastrate Guards<https://www.worldanvil.com/w/tartys-dbzeke/a/bahlastrate-guards-article>

Related Locations

  *   <https://www.worldanvil.com/world/settlement/3c922acd-b2de-48f1-aea5-961280e93a2c/edit> Totharal<https://www.worldanvil.com/w/tartys-dbzeke/a/totharal-settlement>

________________________________

**Comment by Kordishal** [comment] 2023-01-16 08:48
I can't see the same issue as you, but from your paste I don't seem to be able to see everything? Are you using secrets?

![image](https://user-images.githubusercontent.com/14262536/212635668-cf696964-5fb4-48f0-ab0a-31c1844c405c.png)

**Comment by DBZeke5** [comment] 2023-01-20 03:15
Hello Jonas,
I discovered the issue, anytime that I put and indent bbcode [in] in something that will be in the storyteller content it wont display the rest of the article.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Kordishal** [comment] 2023-01-20 11:54
Are you closing the [in] [/in] BBCode around the paragraph?

**Closed by Kordishal** 2023-01-20 11:54 UTC
Labels: Feature: Articles & Templates, Feature: World Presentation, Type: Visual
