### ISSUE TITLE
Unable to Transfer Statblock to Players in World

### ISSUE THREAD

**Issue by eildan** [worldanvil/worldanvil-bug-tracker#1240] opened 2022-08-22 22:29 UTC
**World Anvil Username**:
danboy

**World / Campaign / RPG Character / Manuscript Title**:
Eweca - _All Related Characters_

**Feature**: 
Statblock Permission Transfer

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/sheet/1092389/view

**Describe the Issue**
After following Graylion's step-by-step process as noted [here on the discord](https://discord.com/channels/348060277989965844/380013392653451264/827655000200445994)

**To Reproduce**
1. Go to [Statblock Page](https://www.worldanvil.com/heroes/world/list?type=world)
2. Click on 'Create a new sheet'
3. Make new sheet and click 'View Sheet'
4. Scroll to the bottom
5. User does NOT see 'transfer ownership'
![image](https://user-images.githubusercontent.com/111812418/186029605-0125627f-5bf5-404b-a012-ae58d87de43a.png)

**Expected behavior**
1. Go to [Statblock Page](https://www.worldanvil.com/heroes/world/list?type=world)
2. Click on 'Create a new sheet'
3. Make new sheet and click 'View Sheet'
4. Scroll to the bottom
5. User is ABLE to see 'transfer ownership'
![image](https://user-images.githubusercontent.com/111812418/186029579-217cfc5a-9143-43d1-aeba-d811f1b0bef1.png)

**Comment by graylion-wa** [comment] 2022-08-22 22:44
I spent about an hour with Danboy as his invited player walking through the steps of https://www.worldanvil.com/w/creation/a/invite-characters-article which has not failed me yet for over a year of using these steps. I had him screen shot me at various points through to make sure we were on the same page.

In danboys case we stalled out at step eight, he was not presented with a handover sheet to player drop down box. The sheet was created from scratch and never assign to another. He has the D&D 5e system in his world config. His has RPG character manager enabled and RPG manager. I was at a loss to go further.

**Comment by graylion-wa** [comment] 2022-08-22 22:45
In addition I reversed the process and invited him to my world and had not issues, so the problem seems unique to his world.

**Comment by iamromeo** [comment] 2022-08-23 06:37
In order for the Transfer ownership to be possible ALL 3 of the following must be true: 
1. A campaign should be active
2. The user trying to make the transfer should be the current owner of the sheet
3. The active campaign should have more than 0 characters currently under it. 
This is not a bug.

**Closed by iamromeo** 2022-08-23 06:37 UTC
