### ISSUE TITLE
Categories not staying deleted and Articles not staying in their folders

### ISSUE THREAD

**Issue by Lillydaemon** [worldanvil/worldanvil-bug-tracker#1252] opened 2022-09-05 01:27 UTC
**World Anvil Username**: Lillydaemon

**World / Campaign / RPG Character / Manuscript Title**: Walker Saga

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Categories are not staying deleted and are moving from one world to another. Articles are not staying in the categories where I place them. Sub Categories are making themselves Parent Categories. I noticed that there was an older thread with a similar issue but I was encouraged by the live chat representative to make a new issue about this because the former one had been marked as closed and my issue did not completely match up with the former complaint.

**To Reproduce**
1. I am new to the site so I had multiple tabs open to explore as much of it as I could. When I realized that I could create more than one world, I did so and started working on the two of them at the same time (my brain is chaotic and doesn't like to focus on one thing for too long unfortunately.) I realize that this probably caused some initial problems as with the former complaint and if it had ended there, I wouldn't be making this thread. 
2.  I logged off after working for a while this morning and when I logged back in a little while ago, I immediately went to the "Articles" section to continue editing one that I started this afternoon. (At this point, I only have one tab open in my entire browser and that's the way it stayed throughout this experience). I noticed that some of the Categories that belonged in my world "Sanguilai Saga" had ended up in "Walker Saga". 
3.  I deleted them without seeming issue then went to open the article that I intended to work on only to find that it was not in the Category where I had placed it earlier in the day.
4. I clicked on the "Article" section in order to bring up the "Recently Updated Articles" section so that I could find it. 
5. All of the Categories I had just deleted were back and all of the Sub Categories had become Parent Categories. 

**Expected behavior**
I would like the Categories that I delete to stay deleted and Articles to stay in the folder that I place them in.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Screenshot of Category issues](https://user-images.githubusercontent.com/112834022/188342921-fb2abb80-d34d-45e5-a70e-49cf721f8872.png)

**Comment by Kordishal** [comment] 2022-09-05 06:29
Hi, with the steps you provided I am unable to reproduce this issue. Have you tried moving these categories back? Open the category in editing. Switch to the other world in a different tab. Go save that category.

**Comment by Lillydaemon** [comment] 2022-09-05 11:29
Hi Kordishal, thanks for getting back to me. I wanted to avoid having two tabs open with separate worlds, since that seems to cause issues, so I just deleted the extra ones again. Took 2 more attempts but I finally managed to get the unneeded categories removed. I did, also, switch my web browser. The Live Chat Support Rep suggested that Mozilla Firefox might have trouble running the site correctly and suggested Opera so I switched to that and I haven't had anymore issues today.

**Comment by Kordishal** [comment] 2022-09-05 16:56
Ok that is weird, but good you were able to resolve it. I will close this issue. If anything new comes up with this issue just comment on here again.

Firefox generally should work fine as it is a well supported, modern browser. I hope you have a good experience with World Anvil going forward!

**Closed by Kordishal** 2022-09-05 16:56 UTC
Labels: Type: UI / UX, Status: Cannot Reproduce, Feature: World
