### ISSUE TITLE
Adding Newly Created Heroes Character to Campaign Causes 404

### ISSUE THREAD

**Issue by RiverFang13** [worldanvil/worldanvil-bug-tracker#875] opened 2022-02-17 04:33 UTC
**World Anvil Username**:  RiverFang, but issue first reported on Discord by another user

**Feature**: RPG Features

**Describe the Issue**
After creating a new Heroes character and attempting to add to a campaign via URL, upon selection of the character, a 404 page appears. This issue does not happen with Heroes characters created in the past (roughly 6 months old or older) or characters created through the form on the invite page.

**To Reproduce**
1.  Create Heroes character.
2. Use invite link to attempt to add Heroes character to a created campaign.
3. Receive 404 error & character is not added to the campaign

**Expected behavior**
Any character, whether newly created or old, should be added to the campaign after selecting the character via the campaign invite link.

**Further information**
I tested this issue on both my IS and a free account. Heroes characters that had been created in the past (roughly 6 months old or older) were added to the campaign following the campaign invite link with no issue. Characters created using the character creation form on the invite page also were added to the campaign with no issue. I created multiple new Heroes characters (using new names or just Test) and all characters created today caused a 404 when being invited to the campaign. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

This screenshot shows the only way to currently create a new Heroes character and have it be added to a campaign without a 404, at least that I have found. 
![2022-02-16](https://user-images.githubusercontent.com/65030622/154405810-93873e01-c1af-493e-a28c-910f49571b71.png)

**Comment by iamromeo** [comment] 2022-02-17 05:01
Is that hero already part of that world? If it is - currently it needs to be removed before added to a campaign - Can you confirm this for me River?

**Comment by RiverFang13** [comment] 2022-02-17 05:07
One of the very old Heroes I tested with was already attached to the world, but none of the newly created ones or one of the older ones were not attached to the world.

**Comment by Kordishal** [comment] 2022-02-17 05:10
I just created a character and then invited them to the campaign and it worked fine. So there must be something else going on as well?

**Comment by RiverFang13** [comment] 2022-02-17 05:16
I tested on two accounts with about 4 newly created characters. This came up after someone in the Discord had been struggling all day and I just reproduced their issue. The work around I discovered fixed their issue so I'm not sure what else would cause the 404.

**Comment by iamromeo** [comment] 2022-02-17 05:21
What was the workaround you discovered ?

**Comment by RiverFang13** [comment] 2022-02-17 05:22
Instead of creating the character before trying to join the campaign, it is possible to use the join link and then create a character using the Create a New Character form on the invite page. That was the only way I could create a new character and link it to a campaign without getting an instant 404.

**Comment by iamromeo** [comment] 2022-02-17 05:26
Thank you River - i will investigate

**Comment by iamromeo** [comment] 2022-02-17 05:29
I also cannot reproduce this the way it is explained. 

- Create a new character
- Click on line
- Join Campaign 

Works as intended. This is not the way to reproduce this.

**Comment by iamromeo** [comment] 2022-02-17 05:32
Note: No issue with characters ALREADY in a world joining a campaign

**Comment by iamromeo** [comment] 2022-02-17 05:35
Note: no issue with campaigns with no parties

**Comment by Kordishal** [comment] 2022-02-17 05:38
Ok it happens on my test account the way River described. I am not sure what I did differently though

**Comment by Kordishal** [comment] 2022-02-17 05:39
ah wait I newly created the campaign. Maybe that is the difference?

**Comment by iamromeo** [comment] 2022-02-17 05:40
I have also tested with a newly created campaign - this is not it

**Comment by iamromeo** [comment] 2022-02-17 05:42
@RiverFang13 I will need access to teh account and character / campaing that this occurs can you please message me on Discord
or you @Kordishal

**Comment by iamromeo** [comment] 2022-02-17 10:06
The issue is now fixed and deployed

**Closed by iamromeo** 2022-02-17 10:06 UTC
Labels: Type: UI / UX, Feature: Campaign, Feature: RPG Characters
