### ISSUE TITLE
Linear Navigation not working

### ISSUE THREAD

**Issue by DJWesleySchaegen** [worldanvil/worldanvil-bug-tracker#1344] opened 2022-11-05 19:32 UTC
**World Anvil Username**: DJverne12

**World / Campaign / RPG Character / Manuscript Title**: Forgotten realms

**Feature**: Linear Navigation

**Operating System**: Windows

**Browser**: Chrome

**Device / Device Model**: Laptop

**Related URLS** (To public & visible pages, add screenshots otherwise): https://www.worldanvil.com/w/forgotten-realms-djverne12/a/beneath-candlekeep-landmark 

**Describe the Issue**
There is no linear navigation

**To Reproduce**
1. Go to an article
2. Click on navigation
3. See error

**Expected behavior**
I expect for Linera navigation to work

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment] 2022-11-05 21:02
Please read through current bug reports before submitting one - 

Duplicate of #1336

**Closed by iamromeo** 2022-11-05 21:02 UTC
