### ISSUE TITLE
World Goal continues to reset to 10000 words

### ISSUE THREAD

**Issue by evadye** [worldanvil/worldanvil-bug-tracker#795] opened 2022-01-03 04:02 UTC
**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: Dashboard Word Count

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Word count goal continues to reset itself to 10,000 after being set to zero. 

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Settings'
3. Click on 'Advanced'
4. Scroll down to 'Word Count'
5. Set to '0'
6. Click on 'Save Changes'
7. Refresh screen to confirm changes saved.
8. Go to 'Dashboard'. 
9. Confirm word count goal has **not** been disabled
10. Click on 'Settings'
11. Confirm 'Word Count' has been reset to 10000.

**Expected behavior**
I included this in my steps to reproduce, steps 8-11. When the 'advanced settings' screen is refreshed after setting the word count to '0', the number remains unchanged. As soon as the main Dashboard button is clicked, the word count goal appears to auto-reset itself back to the original goal of 10,000. Other values have been tested ranging in value from 1 - 9867 and the word count works as expected. The 'reset' issue only appears when '0' is the value entered to try and disable the feature.

**Screenshots**
If applicable, add screen shots to help explain your problem. You can add screenshots by drag & drop into this window!

<img width="1680" alt="Word Count Bug - 1" src="https://user-images.githubusercontent.com/88847497/147899154-c27569a2-e38b-41a8-b83c-8a923100bb27.png">
<img width="1680" alt="Word Count Bug - 2" src="https://user-images.githubusercontent.com/88847497/147899153-1d63ed1f-355b-4fda-9f8a-2f8756a2f5ed.png">
<img width="1680" alt="Word Count Bug - 3" src="https://user-images.githubusercontent.com/88847497/147899152-684917ec-039b-414f-8e49-763d010a7153.png">
<img width="1680" alt="Word Count Bug - 4" src="https://user-images.githubusercontent.com/88847497/147899151-00a44424-e990-4d36-8035-3dde70cba48e.png">
<img width="1680" alt="Word Count Bug - 5" src="https://user-images.githubusercontent.com/88847497/147899150-aba5c1b9-94c7-494e-8962-0972209ddad3.png">
<img width="1680" alt="Word Count Bug - 6" src="https://user-images.githubusercontent.com/88847497/147899149-b1f19333-b0c1-450b-9775-16ea976f088a.png">
<img width="1680" alt="Word Count Bug - 7" src="https://user-images.githubusercontent.com/88847497/147899148-f705c948-901d-4dd2-b2df-00ff9783d728.png">
<img width="1680" alt="Word Count Bug - 8" src="https://user-images.githubusercontent.com/88847497/147899147-fc0f0713-4e89-4dfe-8c68-79a6c303a0ab.png">

**Comment by Kordishal** [comment] 2022-01-03 09:24
Duplicate of #778 

Dimi has mentioned that this is not actually implemented. The documentation is wrong.

**Closed by Kordishal** 2022-01-03 09:24 UTC
