### ISSUE TITLE
Unable to view players character sheets

### ISSUE THREAD

**Issue by MidoriOokami** [worldanvil/worldanvil-bug-tracker#964] opened 2022-04-03 19:43 UTC
**World Anvil Username**: Midori Ookami

**World / Campaign / RPG Character / Manuscript Title**: Silvermist, The Everflowing Sea - Campaign

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Up until just a few weeks ago, my DM/World builder and I; the Editor/Author have been able to view the character sheets of the other players in his campaign. DM has not changed any permissions, but suddenly we are no longer able to click on or view character sheets other than our own. (I can read and view my own characters sheet, but I can no longer go to a fellow players character profile to view theirs.) DM has given me editor access to his campaign/world, so I was able to and should still be able to view their sheets. I have walked one of my fellow players through detaching and reattaching their sheet to see if it fixed the issue as per recommendation and it has not fixed the issue.

I know that their sheets are still attached to the character profile, as we can view their base stats beneath their character photo on their profile page and on the campaign page, but neither through their direct profile page nor the campaign page can we view their sheets. None of the players have set their sheets to private either, nor have they removed them from their character. 

**To Reproduce**
Steps to reproduce the behaviour (On character profile page)
1. Go to Character profile page
2. Click on 'Sheet'
3. Scroll down to see nothing where the sheet should be

Steps to reproduce the behaviour (On campaign page)
1. Click on 'Campaign page' on character profile page
2. Scroll down to 'the protagonists' 
3. Select a character and click on the 'eye' icon beside their stats (Note that it is grayed out rather than lit up) 
4. Redirected to the '404' 'thus you have reached the end of this world' page

**Expected behavior**
Ability for the DM/world builder and Myself; the editor/author - to view players character sheets. 

**Screenshots**

https://i.gyazo.com/8c7212baab1169ae9f6f3d743ee34058.png

https://i.gyazo.com/8d0cb170d3b4503b32d42440fd40dda7.jpg

https://i.gyazo.com/41fbc7cdf8e654587af0a8df0d9b3947.png

My own character sheet which I can view as per normal (for comparison): 
https://i.gyazo.com/c2d4dcedc25dd237ac813e7cec9f1bf6.png

**Comment by Kordishal** [comment] 2022-04-03 19:49
probably duplicate of #963

**Comment by iamromeo** [comment] 2022-04-05 06:28
Closed as a duplicate

**Closed by iamromeo** 2022-04-05 06:28 UTC
Labels: Type: Bug, Feature: RPG Characters

**Comment by MidoriOokami** [comment] 2022-04-05 23:42
If this could at least remain viewable, that would be appreciated, as I feel it has more information based around the problem than the entry it was claimed as a duplicate on? Thank you
