### ISSUE TITLE
Creating a new map set to private and with a subscriber group attached fails

### ISSUE THREAD

**Issue by GreatBamboozler** [worldanvil/worldanvil-bug-tracker#74] opened 2021-03-17 16:40 UTC
**World Anvil Username**:  TheGreatBamboozler

**World / Campaign / RPG Character / Manuscript Title**:  Gaelamonde

**Feature**: Create Map

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.  For several weeks I have encountered an issue that when I attempt to upload a new map, it redirects me to the "Error 404, you have reached the end of this world" page.  I had sent an e-mail to the contact team, they instructed me to clear my cache.  If that didn't work, I was instructed to file the issue here.

**To Reproduce**
1. Go to '...' Maps
2. Click on '....' Create Map
3. Scroll down to '....' Upload file, set privacy parameters, then select save and create
4. See error  404

**Expected behavior**
A clear and concise description of what you expected to happen.  My map to upload as it has the countless times I have used this feature in the past.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment] 2021-03-17 17:03
Hi. This does not happen generally.

Is the image smaller than 25 MB?
Is the image a JPG, PNG or WEBP image?

If both of these are not the case then it is usually some type of metadata that prevents the image from being uploaded. Often this can be resolved by re-exporting the image via GIMP or Photoshop.

**Comment by bratta** [comment] 2021-03-17 18:59
I'm having the same issue with uploading maps. The image in question is a 2MB JPG exported from Inkarnate and I've exported it a few times to try to resolve this. I get a 404 when creating a map just like @GreatBamboozler .

**Comment by Kordishal** [comment] 2021-03-17 19:24
Could you attach the images so I can test those? If you do not want to upload an image to a public site like this you can send me the image per DM on Discord to SoulLink#3294. (Dev Gremline role)

This is for both of you.

**Comment by GreatBamboozler** [comment] 2021-03-17 19:46
I actually fixed the issue myself. The other may try this as well. I tried
uploading my maps without setting any privacy restrictions (groups that
could see the content). It then allowed me to upload the map. Afterwards, I
just selected the applicable privacy settings and group visibilities. It
remedied my issue, or at least has acted as a solid work-around to the
issue. It took some tinkering, and experimentation, but I figured it out.
Hope this helps.

**Comment by Kordishal** [comment] 2021-03-17 20:05
That is strange. It would help if you could try to send me the map and all the metadata you added to the form. Most likely there is an issue there.

**Comment by GreatBamboozler** [comment] 2021-03-17 20:17
Here's a copy of the map.  I honestly did not add any metadata to the map
after both attempts (the failed attempt and the successful attempt).  All I
did was change the privacy settings to public, then returned it to the
private state.

**Comment by GreatBamboozler** [comment] 2021-03-17 20:19
Since the successful upload of this map, I have applied my "fix" to the
other maps that wouldn't upload.  So far, it has worked 100% of the time.
I have now uploaded a subsequent 20 maps following the same procedure.  I
have tried it without altering the privacy settings, received the 404
message, then attempted again after the "fix."  Each time was successful.
Yes, this is tedious, but I'm just happy I can continue building my world.

**Comment by Kordishal** [comment] 2021-03-17 20:22
Hi, thanks for your answers. Unfortunately, GitHub can't use email attachments. You would need to actually open the website and then add the map here.

**Comment by GreatBamboozler** [comment] 2021-03-17 20:24
![Emerald Bluffs](https://user-images.githubusercontent.com/80842674/111533514-dcf49e00-8734-11eb-955d-6166fa57b3fb.jpg)

**Comment by bratta** [comment] 2021-03-17 20:29
![Formaria](https://user-images.githubusercontent.com/8271/111534028-8045b300-8735-11eb-985d-dd173742c8fd.jpg)

This is the one I was testing with.

**Comment by bratta** [comment] 2021-03-17 20:30
Also, I tried the trick of not setting any subscriber groups and it allowed the map to save finally.

**Comment by GreatBamboozler** [comment] 2021-03-17 20:33
Glad to hear it!

**Comment by Kordishal** [comment] 2021-03-17 20:38
Ok yeah. So the problem appears when a map is uploaded with both private and a subscriber group selected. Thank you for your patience!

**Comment by iamromeo** [comment] 2021-03-18 03:46
I am sorry I still cannot reproduce @Kordishal 
- go to world/map/new
- add title
- select file
- privacy select private
- subgroups: select 1 sub group

Map uploading as intended

**Comment by iamromeo** [comment] 2021-03-18 03:49
https://user-images.githubusercontent.com/660175/111570486-a444db00-87ad-11eb-9ab4-276cc8927eff.mov

**Comment by Kordishal** [comment] 2021-03-18 06:23
It only happens in public worlds. Private worlds are not affected.

**Comment by iamromeo** [comment] 2021-03-18 13:17
The above case took place on a public world. Is there anything more specific I could try? can you reproduce it in any of your worlds?

**Comment by Kordishal** [comment] 2021-03-18 13:26
Yes. It happens in my world. To be honest I don't know why, but have you tried with one of the images provided above? I feel it started when I used one of these images.

**Comment by iamromeo** [comment] 2021-03-18 14:08
@bratta @Kordishal @GreatBamboozler 
does your world have default subscriber groups ?
and are you adding the default subscriber group
when you are creating the map?

**Comment by bratta** [comment] 2021-03-18 14:18
> @bratta @Kordishal @GreatBamboozler
> does your world have default subscriber groups ?
> and are you adding the default subscriber group
> when you are creating the map?

My world is set to private. I have a default subscriber group called “Players” and one extra for GM’s. When creating the map I added both to the map and got the error. If I leave them out it lets me create it and I can safely add them both when editing.

**Closed** 2021-03-18 14:48 UTC
Labels: Feature: Maps, Priority: Moderate, Severity: Minor, Status: Reproduced, Type: Bug
