### ISSUE TITLE
Manuscript Bug

### ISSUE THREAD

**Issue by CyrusCerf** [worldanvil/worldanvil-bug-tracker#376] opened 2021-06-18 14:30 UTC
**Laeris**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**THe manuscript plug in isn't working correctly. Please, fix soon, if you can. I use this to write often and is my preferred way to write.**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment] 2021-06-18 14:58
Duplicate of #375

**Closed by Kordishal** 2021-06-18 14:58 UTC
