### ISSUE TITLE
Article content doesn't show

### ISSUE THREAD

**Issue by Rosaa-xd** [worldanvil/worldanvil-bug-tracker#582] opened 2021-09-22 08:07 UTC
**World Anvil Username**: Sh4d0wPh03n1x

**World / Campaign / RPG Character / Manuscript Title**: Hesli

**Feature**: Article View

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/hesli-sh4d0wph03n1x/a/altiuiri-di-marfedelom-vehicle?preview=true

**Describe the Issue**
A clear and concise description of what the issue is.

The CSS of article content seems to have "disappeared". Article content isn't shown (headers and titles are as far as I'm aware). I have attached a screenshot of the CSS that I was able to get which could explain the issue.

This issue has been reported by multiple users in the #help channel on Discord.

**To Reproduce**
1. Go to https://www.worldanvil.com/w/hesli-sh4d0wph03n1x/a/altiuiri-di-marfedelom-vehicle?preview=true
2. View page

**Expected behavior**

The expected behaviour is that the article content is shown.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
<img width="298" alt="Screenshot 2021-09-22 at 09 59 27" src="https://user-images.githubusercontent.com/11375483/134306487-3ad80d72-b540-4390-95a2-12b1df52eb82.png">
<img width="1225" alt="Screenshot 2021-09-22 at 09 45 03" src="https://user-images.githubusercontent.com/11375483/134306290-59fa0cdb-637d-4f2c-95fc-b5b651210aa6.png">

**Comment by Rosaa-xd** [comment] 2021-09-22 08:08
Oops, I added the wrong CSS screenshot, here is the correct one
<img width="298" alt="Screenshot 2021-09-22 at 09 59 27" src="https://user-images.githubusercontent.com/11375483/134306487-3ad80d72-b540-4390-95a2-12b1df52eb82.png">

**Comment by MGatta** [comment] 2021-09-22 08:15
As mentioned in #help, this seems to be widespread. I have removed the CSS, but it still does not show my content so I am not sure the issue is CSS:
![image](https://user-images.githubusercontent.com/80196715/134307354-73e84cdc-61df-4469-840f-46d62cfd55e4.png)
[Page link](https://www.worldanvil.com/w/13-mgatta/a/-an-industrial2C-mining2C-logging-or-other-production-settlement----sc2021-sponsored-prompt-article?preview=true)

**Comment by MGatta** [comment] 2021-09-22 08:20
Note: Storyteller content does show when clicked
![image](https://user-images.githubusercontent.com/80196715/134308162-6fec7b4d-76bc-496b-914d-4553443dddbc.png)

**Comment by silverpanther** [comment] 2021-09-22 08:48
I have the exact same issue.

**Comment by iamromeo** [comment] 2021-09-22 08:57
Please do not report bug again if they are already on the board 
duplicate of #580

**Closed by iamromeo** 2021-09-22 08:57 UTC
