### ISSUE TITLE
Species template side bar content panel renders even when empty

### ISSUE THREAD

**Issue by RobinJHills** [worldanvil/worldanvil-bug-tracker#559] opened 2021-09-13 16:43 UTC
**World Anvil Username**:
RJHills
**World / Campaign / RPG Character / Manuscript Title**:
Dwalen
**Feature**: 
Species te;plate
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/dwalen-rjhills/a/humans-species
**Describe the Issue**
When creating a new article with the species template the content panel for the sidebar is always rendered. Even when there has been no content provided for this part. 

This results in a box with shaded border rendering that is just empty. 

**To Reproduce**
1. Create a new species article.
2. View the species article.
3. look at where the side bar content panel sits.
4. See the empty box.

**Expected behavior**
It would make more sense for the box to not render when it is empty. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Capture](https://user-images.githubusercontent.com/90207615/133123759-552dada1-9a64-4736-9126-fb3bc45dedd3.JPG)

**Comment by happyskunk** [comment] 2021-09-13 17:05
just for extra clarity, the issue isn't that there is a side bar at all, but that the box renders with nothing in it. this doesn't happen on all templates (and we're not 100% sure its not intentional)

i went through all the article types and found it happens on vehicle, building, species, conflict, organization, settlement, formation, plot, character, language, material, location, and item... but none of the other articles. 

at first i thought it was just the speices, so thought it might be an oversite and suggested them to make a bug report. 
but now i'm not so sure. 
seems half the article types have the box show up with nothing in it, and the other half don't give the box.

**Comment by iamromeo** [comment] 2021-09-13 17:46
Honestly guys this is quite an edge case and I do not think I will be addressing this - I will have a look tomorrow if it's a quick fix. If it is not, I will be closing this ticket with no further action

**Comment by iamromeo** [comment] 2021-09-14 08:01
This will require an overhaul of the templates that will take a disproportionate amount of time compared to the returned benefit AND because of the checks that will need to be made will make them more complicated to code, and much slower to load. 

Based on the above, this will not be actioned.

**Closed by iamromeo** 2021-09-14 08:01 UTC
Labels: Type: UI / UX, Feature: World Presentation, Type: Visual

**Comment by happyskunk** [comment] 2021-09-15 14:07
ah bummer, thanks for looking into it though!
