### ISSUE TITLE
Bug when posting new entry in the journal

### ISSUE THREAD

**Issue by Gwihir** [worldanvil/worldanvil-bug-tracker#965] opened 2022-04-03 22:50 UTC
**World Anvil Username**: Gwihir

**World / Campaign / RPG Character / Manuscript Title**: Myrdalim / Myrdalim Antique / Aelys

**Feature**: Aelys's Journals

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/hero/journal/list

**Describe the Issue**
When I try to post a new entry in the journal, I can write everything, choose the date and everything, but when I validate, instead of adding a new entry in the day, it sends me to a 404 page.

**To Reproduce**
1. Go to 'Journal'
2. Click on 'Add an entry'
3. Write down an article, and then click to 'post'
4. See error, page 404

**Expected behavior**
I just want to see a new entry in my journal

**Screenshots**
I think you see the problem. :)

**Comment by Kordishal** [comment] 2022-04-04 06:17
This is most likely caused by invalid characters within the text. Most emojis and other large unicode characters cannot be stored by World Anvil.

**Comment by Gwihir** [comment] 2022-04-04 09:36
The text is this one, in french : 

```
[justify]Vu que nous nous inquiétons, nous allons voir au temple de Lathandre… Car nous venons d’apprendre que la prêtresse peut parfois disparaitre plusieurs jours voire même plusieurs mois, sans que personne ne sache trop où elle ne va ni ce qu’elle fait… Les membre de son clergé savent que cette absence serait une absence de plusieurs semaines. Là, nous apprenons que nos amis sont partis faire une enquête sur des disparitions au sein d’une communauté voisine… Mais ne rien entendre de leur part depuis ce temps, nous fait nous inquiéter surtout suite à la note de Mélania que nous avions de leur part et qui nous demandait de les attendre quatre jours.[/justify]
[center][i]« Chers Amis, nous allons bien même si certains d'entre nous ont pris un petit coup de chaud. Nous nous sommes absentés pour régler une affaire urgente qui reste cependant dans nos cordes. Si nous ne sommes pas revenus dans quatre jours, inquiétez-vous et demandez à Mystel.
M. »[/i][/center]
[justify]Les quatre jours sont écoulés, nous allons donc… nous inquiéter et partir en route à la recherche de nos amis à bord du Sipe-Lin. Nous décollons sans encombre et nous savons que nous allons avoir environ une journée de route pour rejoindre la communauté. [/justify]
```

I saw a bug with the letter **ë** who make me get the 404 error each time, but now, I don't see any special character and I still got the 404 error page.

**Comment by Kordishal** [comment] 2022-04-04 09:55
It appears that this section causes the issue:

`[justify]Vu que nous nous inquiétons, nous allons voir au temple de Lathandre… Car nous venons d’apprendre que la prêtresse peut parfois disparaitre plusieurs jours voire même plusieurs mois, sans que personne ne sache trop où elle ne va ni ce qu’[/justify]`

@ DImitris: I was unable to figure out a smaller example that causes this bug, but there is definitely an issue here that should not occur.

**Comment by Kordishal** [comment] 2022-04-04 09:56
It also doesn't happen in general if no [justify] BBCode is present. And when editing a journal entry and adding this same content it saves without a problem.

So the problem appears only in the journal creation form

**Comment by Gwihir** [comment] 2022-04-04 10:58
Okay, it's strange because I already used [justify] in my previews messages and I never got the 404 error page before. 
But I understand, I will edit my text after posting it each time to avoid the bug. Thanks a lot for the help. :)

**Comment by Kordishal** [comment] 2022-04-04 11:02
No need to close the issue, Dimitris will do that either after fixing the issue or if it is tabled for later.

**Comment by iamromeo** [comment] 2022-04-05 06:32
The issue is : **inquiétons** specifically one of those accented letters is not part of the UTF8 set (is a special character not supported)

**Closed by iamromeo** 2022-04-05 06:32 UTC
Labels: Type: Bug, Status: Reproduced, Feature: User Interface
