### ISSUE TITLE
Interface setting saving 404 error

### ISSUE THREAD

**Issue by solstislucifer** [worldanvil/worldanvil-bug-tracker#281] opened 2021-05-21 19:58 UTC
**World Anvil Username**:
petergao96
**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 
Saving changes on interface
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/dashboard/user/interface
**Describe the Issue**
After changing my interface setting for the first time, i wanted to switch again. Now it's throwing a 404 error every time.
**To Reproduce**
1. Go to 'https://www.worldanvil.com/dashboard/user/interface'
2. Click on 'Saving changes'
3. See error

**Expected behavior**
Expected it to save properly

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/80777982/119191893-3fc42780-ba4d-11eb-985d-2cde2b3f3d38.png)
![image](https://user-images.githubusercontent.com/80777982/119191916-45ba0880-ba4d-11eb-9d8a-937ca6742651.png)

**Comment by Kordishal** [comment] 2021-05-21 21:20
Duplicate of #270

**Closed by Kordishal** 2021-05-21 21:20 UTC
