### ISSUE TITLE
Can't create map markers

### ISSUE THREAD

**Issue by adajd** [worldanvil/worldanvil-bug-tracker#80] opened 2021-03-21 05:06 UTC
**World Anvil Username**: AdaJDouglass

**World / Campaign / RPG Character / Manuscript Title**: Ada's Traveller Universe

**Feature**: Maps

**Related URLS** (To public & visible pages add screenshots otherwise): N/A

**Describe the Issue**
Every time I try to add a new map marker, it just sends me to the 404 page.

**To Reproduce**
1. Go to '...': Maps
2. Click on '....': Edit
2a. Fill in marker details
3. Scroll down to '....': Create Marker
3a. Click on it
4. See error: 404 page

**Expected behavior**
I expected to be able to create a map marker.

**Screenshots**
It's the 404 page. I'm sure you've seen it.

**Comment by Kordishal** [comment] 2021-03-21 07:55
Cannot reproduce this issue. Please come by the [Discord](https://www.worldanvil.com/discord) to help figure this out.

**Comment by adajd** [comment] 2021-03-23 15:42
I just joined the Discord. Which channel is the appropriate one to ask about this in?

**Comment by iamromeo** [comment] 2021-03-24 04:34
#development-discussion or #help

**Comment by iamromeo** [comment] 2021-03-25 09:23
Hey @Kordishal @adajd do we have an update on this? I haven't had anyone else reporting something like this
DO we have any more information on this or shall I close it?

**Closed** 2021-03-25 09:50 UTC
Labels: Feature: Maps, Status: Cannot Reproduce
