### ISSUE TITLE
Global cover image credit is used for any image without a credit itself used as a cover

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#308] opened 2021-06-03 14:47 UTC
**World Anvil Username**: MGatta

**Feature**: Gobal cover image for articles

**Related URLS** (To public & visible pages add screenshots otherwise):
[Article using global cover image](https://www.worldanvil.com/w/albion-sakarami/a/hills-of-faranur-location)
[Article using a different cover image, with the wrong credit](https://www.worldanvil.com/w/albion-sakarami/a/arvanta-settlement)

**Describe the Issue**
When a world has a global cover article with a credited artist, that credit is assigned to all articles with different cover images which do not have credited artists themselves.

**To Reproduce**
1. Make use of a global cover for articles and make sure that image has a credited artist
2. Add an image without a credit
3. Create an article and design the creditless image as the cover
3. Scroll down to the credits section

**Expected behavior**
For images without a credited artist to not show anything / For images not to be wrongly credited.

**Comment by iamromeo** [comment] 2021-06-04 12:15
I am sorry but I cannot make heads or tails of this "When a world has a global cover article with a credited artist, that credit is assigned to all articles with different cover images which do not have credited artists themselves."

**Comment by Kordishal** [comment] 2021-06-04 14:06
1. She means the Default Global Cover image. Which can be assign in Styling and is shown on every article of the world.
2. The cover credits appear at the bottom of the article.
3. The issue is in the case that the Default Global Cover HAS credits and the local ARTICLE HEADER image does NOT. Then the credits are shown as if the local header was made by the person who made the global one.

**Comment by MGatta** [comment] 2021-06-04 14:46
Sorry if it was not clear. To add visual clarifications in addition to what Soul said:

""When a world has a global cover article with a credited artist"
![image](https://user-images.githubusercontent.com/80196715/120819414-d9aec880-c553-11eb-868f-c6174fbeba07.png)
![image](https://user-images.githubusercontent.com/80196715/120819502-eb906b80-c553-11eb-906a-f8c113de97b9.png)

 "that credit is assigned to all articles with different cover images which do not have credited artists themselves."
![image](https://user-images.githubusercontent.com/80196715/120819754-2a262600-c554-11eb-996e-e17b0e5e69bd.png)
![image](https://user-images.githubusercontent.com/80196715/120819791-34482480-c554-11eb-9fa1-a49a916e3ee6.png)

**Comment by iamromeo** [comment] 2021-06-08 03:42
This should be fixed now (well in about 20 minutes will be deployed)

**Comment by KajetanWrites** [comment] 2021-06-10 15:51
I noticed that now the global cover credit is not displayed

**Comment by KajetanWrites** [comment] 2021-06-10 15:55
it's absent from every article

**Comment by graylion-wa** [comment] 2021-06-10 15:57
This update may have affected the global cover credits showing at all.

This is an article with an article cover, which is correct.

![20210610_115414.jpg](https://user-images.githubusercontent.com/79761754/121557568-d8ade900-c9e2-11eb-8852-bdfe32295255.jpg)

This is an article using the global cover which is now missing global cover credits. This may not be correct, im not sure.

![20210610_115447.jpg](https://user-images.githubusercontent.com/79761754/121557703-f7ac7b00-c9e2-11eb-8c5a-1856025dde75.jpg)

This used to have a credit to TimePool who designed my logo.

Thank you

**Comment by iamromeo** [comment] 2021-06-10 19:14
should now be fixed

**Closed by iamromeo** 2021-06-10 19:15 UTC
Labels: Feature: Images, Feature: World Presentation, Severity: Trivial, Status: Done, Type: Bug
