### ISSUE TITLE
Map images not showing up even when trying to change them.

### ISSUE THREAD

**Issue by Stigthesheep** [worldanvil/worldanvil-bug-tracker#585] opened 2021-09-23 19:12 UTC
**World Anvil Username**: StigThesheep

**World / Campaign / RPG Character / Manuscript Title**: Voletaria

**Feature**: MAPS

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I have a bug that all my images (only 2) won't show up. The second thing is that when i try to replace the primary image to try and fix it, no image shows. If i load the image in another map it does however show up.

All i see at the moment are the markers and a gray background

**To Reproduce**
I have not been able to reproduce it.

**Expected behavior**
The map shows itself in the background with the markers in the front.

**Screenshots**
![image](https://user-images.githubusercontent.com/91286008/134568547-35719eca-a36a-453c-979b-5d7e548efc1d.png)
*image 2 shows that the map won't show on the UPDATE MAP PRIMARY IMAGE screen*
![image](https://user-images.githubusercontent.com/91286008/134568605-40080e42-d305-4be1-816f-d9f319773f82.png)
*Image 3 shows that the map will show when i make a new map from scratch. *
![image](https://user-images.githubusercontent.com/91286008/134568814-52dfc8c7-ddb0-451c-be3c-5b5523a5ee53.png)

**Comment by Stigthesheep** [comment] 2021-09-23 19:34
For more context the image shows on different locations:
- In the image and files viewer
- On the Home page of the world

**Comment by Kordishal** [comment] 2021-09-23 19:44
the most likely cause is that the map fails to load the image due to a error while loading. Can you link the actual map? That might help.

Otherwise, what you can try is removing the markers you added the latest as they might cause the loading to fail when they are corrupted.

**Comment by iamromeo** [comment] 2021-09-24 03:30
- Do you use custom markers?  - IF you do you have special characters or quotation marks on their title? 
- Do you use in the title or description of any of your markers special characters like quotation marks ' " `

**Comment by Stigthesheep** [comment] 2021-09-24 03:56
> the most likely cause is that the map fails to load the image due to a error while loading. Can you link the actual map? That might help.
> 
> Otherwise, what you can try is removing the markers you added the latest as they might cause the loading to fail when they are corrupted.

I Will try that when I'm home. The map has 60+ markers all with discriptions.

**Comment by Stigthesheep** [comment] 2021-09-24 03:58
> - Do you use custom markers?  - IF you do you have special characters or quotation marks on their title? 
> - Do you use in the title or description of any of your markers special characters like quotation marks ' " ` 
> - What was the most recent changes you have done ot your map in terms of adding markers or content before it stopped displaying correctly? 
> 
> Your content from what I can see is private. If you wish for @Kordishal or myself to investigate you will need to add
> - DImitris
> - SoulLink 
> as COOWNERS in the world (tempirarily) :) 


I Will add you as soon as i can.
I dont use any custom markers.
What i do use are special quotation marks in titles and discriptions.

**Comment by Stigthesheep** [comment] 2021-09-24 04:05
Added the coownership.

**Comment by Kordishal** [comment] 2021-09-24 05:56
Hi, so the image is showing up for me when I look in the editor or in the presentation. Did you resolve the issue on your end? Otherwise I would say the issue is related to an extension in your browser. Try looking at the map in a private / incognito window in the browser of your choice.

![image](https://user-images.githubusercontent.com/14262536/134625221-cee7bf1c-a208-4dbd-adff-165430721e3a.png)

**Comment by iamromeo** [comment] 2021-09-24 10:35
I also can see both the map on preview and live view

**Comment by Stigthesheep** [comment] 2021-09-24 16:28
The Problem seems to be a an faulty update to my chrome browser. I reinstalled and it fixed itself.
Thank you for looking anyway.

**Comment by Stigthesheep** [comment] 2021-09-24 16:40
Ok nevermind, i reproduced the bug after adding an article to a marker.

**Comment by Kordishal** [comment] 2021-09-24 17:41
Still works on my end. Have you tried looking at it in the private / incognito window?

**Comment by Stigthesheep** [comment] 2021-09-24 17:42
Yes i have tried that, it does not work. It does work in Edge browser.

**Comment by Kordishal** [comment] 2021-09-24 18:09
Have you tried cache refresh? CTRL+F5?

**Comment by Stigthesheep** [comment] 2021-09-24 18:17
It does nothing. I have also turned of all my extensions.

**Comment by Kordishal** [comment] 2021-09-24 18:39
Are Dahut, Sirius, Piranesi Markers without anything? They do not show any tooltips and when they are clicked they open the sidebar but its empty.

For Dimitris:
![image](https://user-images.githubusercontent.com/14262536/134724347-b4c1759d-6adc-4bf0-a106-463729c856e2.png)
Found these two error when opening the map. Not sure if related.

**Comment by Stigthesheep** [comment] 2021-09-24 18:46
They don,t have discriptions yet. And are empty labels except for the label text and a Tag called 'Town'

**Comment by Stigthesheep** [comment] 2021-09-24 18:48
I get these errors 
![image](https://user-images.githubusercontent.com/91286008/134725346-f1195b2d-5b01-47c8-98a0-a4ae0dcf0f34.png)

**Comment by Stigthesheep** [comment] 2021-09-24 18:50
The problem started when i started the day i added articles and map embeds to the markers: Greymarsh and Deleau plains

**Comment by Kordishal** [comment] 2021-09-24 19:18
Have you tried removing those? The links or the full markers?

**Comment by Stigthesheep** [comment] 2021-09-24 19:33
I deleted the links. no change. If it helps the map also won't show if I embed it. It's currently embedded in the regions articles

**Comment by Kordishal** [comment] 2021-09-24 20:43
How large is the image? In MB

**Comment by Kordishal** [comment] 2021-09-24 21:18
I am asking because when I open up the map in Brave (Chromium based browser) it lags and loads very slow. I suggest you try to convert the base image to WEBP format and compress it a bit that way. Then try it with that smaller image.

**Comment by Stigthesheep** [comment] 2021-09-24 21:23
16,7Mb

**Comment by Kordishal** [comment] 2021-09-24 21:25
Yeah that is huge. Try to reduce the size to something manageable.

**Comment by iamromeo** [comment] 2021-09-27 15:42
16.7 is not huge - you can have up to 25mb but if your connection or your PC cannot handle it you will have an issue. I would suggest optimizing the original image on it's original size. If you can send it to me at hello@worldanvl.com I will see what I can do to help you out :)

**Comment by iamromeo** [comment] 2021-09-27 15:42
I am closing this since it's not a bug but I will be very happy to help you :) send me the ORIGINAL dimensions files so I can optimize it for you

**Closed by iamromeo** 2021-09-27 15:42 UTC
Labels: Status: Cannot Reproduce, Feature: Maps, Severity: Minor

**Comment by Kordishal** [comment] 2021-09-27 17:40
Sorry! I did not mean to change the resolution of the image (as in width / height) but to use compression to reduce the size in MBs.

You can use GIMP or an online tool to export the file as a WEBP image or use Dimitris offer! 

On my laptop I didn't have an issue with the image in firefox, but I did have issues with Brave so there might be some limitation with Chrome like browsers.
