### ISSUE TITLE
Linear Navigation seems to be broken at the moment. 

### ISSUE THREAD

**Issue by DMFW** [worldanvil/worldanvil-bug-tracker#1338] opened 2022-11-04 17:36 UTC
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: DMFW

**World / Campaign / RPG Character / Manuscript Title**: Discontinuum

**Feature**: Linear Navigation.

**Operating System**: Windows 10

**Browser**: Chrome

**Device / Device Model**:

**Related URLS** (To public & visible pages, add screenshots otherwise):
https://www.worldanvil.com/w/the-discontinuum-dmfw/a/limit-of-navigation-article

**Describe the Issue**
This seems to be affecting all articles that had linear navigation added to them but a nice simple example is the page linked above. Where the navigation to the named articles (forward and backward) would normally appear, we instead see what look like the underlying GUID codes for the articles (a database key I guess?) and the links themselves don't work (they go to a 404 error page). Also it seems to be no longer possible to edit linear navigation for a page within the navigation editing function. 

**To Reproduce**

Go to the bottom of the page where there are left and right pointing linear navigation links. Observe that they have coded text rather than the text that should be the title of the associated article. Observe that the links do not work but generate a 404 error. Observe that it is not possible to add linear navigation when editing an article anymore.

**Expected behavior**

Linear navigation links should connect to the articles assigned to them when the page navigation was defined. This used to work until relatively recently (at least at the beginning of the week) so I assume it was accidentally broken by some fairly recent change. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment] 2022-11-04 18:06
duplicate of #1336

**Closed by Kordishal** 2022-11-04 18:06 UTC
