### ISSUE TITLE
Undeletable Manuscript

### ISSUE THREAD

**Issue by GunplaGoblin** [worldanvil/worldanvil-bug-tracker#974] opened 2022-04-09 19:38 UTC
**BurningGod**:

**Home and The Name of the Manuscript**:

**Feature**: 

**[Related URLS** (To public & visible pages add screenshots otherwise](https://www.worldanvil.com/community/manuscripts/read/2478685382-burninggod-home) and https://www.worldanvil.com/community/manuscripts/read/4580132316-burninggod-the-name-of-the-manuscript:

**Unable to Delete Manuscripts**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**
To select Delete, type of the name of the manuscript and it be gone

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment] 2022-04-09 19:56
duplicate of #206

**Comment by Kordishal** [comment] 2022-04-09 19:56
You can attempt to resolve this issue by removing content and moving about sections within the manuscript.

**Closed by Kordishal** 2022-04-09 19:56 UTC
