### ISSUE TITLE
Problem With The New Chronicles Feature

### ISSUE THREAD

**Issue by Z-Rise** [worldanvil/worldanvil-bug-tracker#1161] opened 2022-07-14 22:57 UTC
Z.Rise
 
Avedo Kingdom

Timelines - Chronicles

I recently bought the Master's membership and started with the Chronicles feature. I tried to make a new chronicle timeline, but the first screen, I guess an image is supposed to be there, but it only loaded. When I clicked the next button, The Choose Calendar Template screen, I'm unable to click the next button again to proceed through the setup. Please help, I'm super excited to use this feature and looking forward to great things!

Steps:

- Go to the "Timelines"  feature.
- Click "Create New Chronicle."
- See Error

Not sure what was supposed to happen, it's my first time.

Thanks!

**Comment by Z-Rise** [comment] 2022-07-14 23:01
Also, I contacted World Anvil via email, and Liana recommended logging out and then back in again, and if that didn't work, to file a bug report. I did try logging out/in, but it didn't work, so here I am!

**Comment by Kordishal** [comment] 2022-07-15 05:35
Are you on Safari? Then this is a duplicate of #1148. If that is the case please try to use the chronicle in a modern browser.

Otherwise the team will have a look.

**Closed** 2022-07-15 10:41 UTC
Labels: Type: UI / UX, Feature: Chronicles

**Comment by Z-Rise** [comment] 2022-07-16 21:19
I downloaded Chrome and Firefox on my iPhone 12 and it still didn’t work.

**Comment by Kordishal** [comment] 2022-07-17 05:36
Can you try it on a different device? iPhones should be supported just to see if this is the cause. Otherwise I am not sue what else could be the cause.

**Comment by Z-Rise** [comment] 2022-07-18 17:08
Ok, I’ll try that and let you know if it works. Thanks!
