### ISSUE TITLE
Article doubled after searching for it

### ISSUE THREAD

**Issue by KajetanWrites** [worldanvil/worldanvil-bug-tracker#1073] opened 2022-06-08 13:56 UTC
**World Anvil Username**: KajetanWrites

**World**: Magic Earth

**Feature**: Articles & Categories

**Describe the Issue**
I searched for an article in the Articles & Categories and it appeared twice. Both links lead to the same article. It also the only situation this happens. As I was checking other articles I found one more such situation, but I don't know the exact number of "affected" articles.

**Screenshots**
![wtf world anvil](https://user-images.githubusercontent.com/80585282/172633877-c1c75dd7-1759-4be9-af4b-7443facb1245.png)

**Comment by KajetanWrites** [comment] 2022-06-08 13:58
As I was checking I was finding more and more such situations

**Comment by Kordishal** [comment] 2022-06-08 14:11
Duplicate of #1058

**Closed by Kordishal** 2022-06-08 14:11 UTC
