### ISSUE TITLE
Privacy settings for markers are not respected when others view the markers.

### ISSUE THREAD

**Issue by moonflower-writer** [worldanvil/worldanvil-bug-tracker#1237] opened 2022-08-21 02:24 UTC
**World Anvil Username**: moonflower-writing

**World / Campaign / RPG Character / Manuscript Title**: Game of Tomes

**Feature**:  Chronicles

**Related URLS** (To public & visible pages add screenshots otherwise): [Chronicle](https://www.worldanvil.com/w/game-of-tomes/chronicle/the-history-of-the-got-verse-chronicle)

**Describe the Issue**
A clear and concise description of what the issue is.

When creating a map pin location in the chronicle, there is a "Privacy" Tab. When I set this to Private and selected subscriber groups then hit "Update" and closed it, I found that it was set to public still when I reopened the page to edit something.

**To Reproduce**
1. Go to Chronicles
2. Create a Map Pin Location
3. Go to the Privacy Tab
4. Set to Private
5. Click the update button
6. Exit out of area
7. go back in area
8. go to privacy tab
9. See error

**Expected behavior**

I would expect the map pin location to remain private with the subscriber groups I set after setting the pin to those settings.

**Screenshots**

![error 1](https://user-images.githubusercontent.com/65192140/185772627-cbd90c14-438c-4a75-94aa-02028976d3f2.png)

![error 2](https://user-images.githubusercontent.com/65192140/185772616-dc289b0a-0b77-44ff-a2d9-77039a0bd59e.png)

**Comment by Kordishal** [comment] 2022-08-21 05:17
It doesn't save anchor position either!

**Comment by Xuroth** [comment] 2022-09-15 23:49
Update: The original issue should have been resolved, but I missed your comment, Kordishal! I'll investigate that!

**Comment by tankus157** [comment] 2022-11-09 02:26
Hi, this issue might be resolved, but the feature isn't working. All my players can see all the makers regardless of the privacy setting. Only the events linked within that are present or not depending on privacy of the event.

**Comment by terekhovpd** [comment] 2022-11-19 23:15
@Xuroth please take note that currently private status is saved, but I still see private markers on the map when I open the chronicles in an incognito window. Please take a look

**Comment by Kill3rh4s3** [comment] 2023-01-08 15:59
Its not fixed all players can see private markers

**Comment by RealPaulquappe** [comment] 2023-01-09 18:13
@Kill3rh4s3 i think this one is fixed. the issue was, that the setting "private" did not save even after saving the progress. on the next loading of the map the setting was "public" again. this is now fixed, no issue anymore. the other one, "our" ticket, is an other problem.

**Comment by tankus157** [comment] 2023-01-09 19:09
> @Kill3rh4s3 i think this one is fixed. the issue was, that the setting "private" did not save even after saving the progress. on the next loading of the map the setting was "public" again. this is now fixed, no issue anymore. the other one, "our" ticket, is an other problem.

NO IT'S NOT! Yes the tag is "saved" to private, but the private setting is not applied as other people than the ones with the rights are able to see it.

**Comment by RealPaulquappe** [comment] 2023-01-09 19:18
> > @Kill3rh4s3 i think this one is fixed. the issue was, that the setting "private" did not save even after saving the progress. on the next loading of the map the setting was "public" again. this is now fixed, no issue anymore. the other one, "our" ticket, is an other problem.
> 
> No it's not! Yes the option is "saved" to private, but the private setting is not applied as other people than the ones with the rights are able to see it.

That is exactly why i think this have to be two different tickets. First the Setting, Second the actual functionality. Obviously they are not as linked as one might guess. It clearly is not functioning. But the here statet issue, that the setting is not saved, is now fixed.

**Comment by Kill3rh4s3** [comment] 2023-01-10 14:02
Thank u for updating the title but the disprition can be foudn in my ticket which got closed

**Comment by Kill3rh4s3** [comment] 2023-01-10 14:03
I was About to Spoil my entire campaign with this its very important

**Comment by Kill3rh4s3** [comment] 2023-01-10 14:04
https://github.com/worldanvil/worldanvil-bug-tracker/issues/1407 This one is the issue

**Comment by Xuroth** [comment] 2023-01-11 19:38
Confirmed: issue is not with form, but with backend validation due to some recent changes.
I am in process of identifying and fixing all permissions issues in Chronicles.

**Comment by Xuroth** [comment] 2023-01-13 17:59
I've deployed some fixes to the server, and tested (below). It appears to be working for me, so I wanted to share the aspects I'm examining/testing.
I've set up a Chronicle and added a subscriber group to a pin. With the current fix in place, the following are true:
a) Unauthenticated (not logged in) users do NOT see the private pin
b) Authenticated users who are NOT in the selected subscriber group can NOT see the pin
c) Authenticated users who ARE in the subscriber group CAN see the pin
d) Owners, Co-Owners - regardless of subscriber group, CAN see the pin (and can edit)

Again, I believe the issue is now resolved. Please let me know if you continue to experience the same issues!

If you'd like, here's the results of the testing:
Here's the [Chronicle](https://www.worldanvil.com/w/WorldAnvilCodex/chronicle/story-of-chronos-chronicle)!
(The pin should be Auxylgard, above the label of the same name on the map - it should look like a flask)

Editor View:
![image](https://user-images.githubusercontent.com/3972262/212387883-61ef1177-1709-481e-8c19-ea9d3cc2e97f.png)

User (without subscriber group) View:
![image](https://user-images.githubusercontent.com/3972262/212388012-b01cf641-ab8d-4563-8f08-0669e1921540.png)

**Comment by Kordishal** [comment] 2023-01-13 22:13
I can confirm as well that the issue seems to be fixed! Will close this, feel free to comment should there be something missed.

**Closed by Kordishal** 2023-01-13 22:13 UTC
Labels: Type: Bug, Severity: Important, Status: Done, Feature: Chronicles

**Comment by Kill3rh4s3** [comment] 2023-01-14 22:33
> I can confirm as well that the issue seems to be fixed! Will close this, feel free to comment should there be something missed.

Can confirm it is fixed but they is another thing.
The Pin will not save the Anchor Position

**Comment by Kordishal** [comment] 2023-01-15 07:08
looks like Xuroth forgot to note that in his todos. I think its best to make a new issue on that!
