### ISSUE TITLE
Timelines are not displaying Characters

### ISSUE THREAD

**Issue by FreyaWa** [worldanvil/worldanvil-bug-tracker#770] opened 2021-12-22 15:21 UTC
**World Anvil Username**:
Gerugaval
**World / Campaign / RPG Character / Manuscript Title**:
The Gates
**Feature**: 
Timelines
**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/the-gates-gerugaval/t/campaign-timeline-timeline
**Describe the Issue**
A clear and concise description of what the issue is.
Timelines are no longer displaying related characters. I have characters selected for the event but they are no longer being displayed. Each event used to have pictures and links for each character involved, this is no longer the case. 
**To Reproduce**

Simply create an event for a timeline, add a character, view the timeline and see that there are no listed characters for that event. 
**Expected behavior**
I would expect the characters to be visible as they used to be. 
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment] 2021-12-22 15:59
Are any of the related characters private articles?
Are any of the related characters draft articles?

**Comment by FreyaWa** [comment] 2021-12-22 16:02
Most, if not all, are public and published. Though, that being said, I did have some that were drafts that still showed up before. 

I double checked several of the involved characters just to confirm that they are published and public.

**Comment by juldum54** [comment] 2021-12-22 23:33
This might be related to `[the issue](https://github.com/worldanvil/worldanvil-bug-tracker/issues/769)` I created some days ago, because now I can't see any character like you, even if  the articles are published.

**Comment by iamromeo** [comment] 2021-12-23 03:18
Fix is being deployed I am sorry about that -  a random typo escaped into the code

**Comment by oncomingshower** [comment] 2022-01-06 16:17
Hi there! I'm having this issue. None of my characters were drafts, I changed them to published and public. They still aren't showing up on my timeline. 

![image](https://user-images.githubusercontent.com/93845397/148414173-b7fa9551-32f9-461e-a098-62ab5e50c203.png)
![image](https://user-images.githubusercontent.com/93845397/148414217-530514f9-003b-4c73-a142-963128997761.png)

Here is an example of my timeline and the people that should be showing up but only the organisation does.

**Comment by iamromeo** [comment] 2022-01-06 16:34
I can confirm this - will investigate

**Comment by iamromeo** [comment] 2022-01-07 08:15
Properly fixed now

**Closed** 2022-01-13 03:33 UTC
Labels: Type: Bug, Feature: Timelines & Events
