### ISSUE TITLE
Calendar Gap

### ISSUE THREAD

**Issue by arcfox4** [worldanvil/worldanvil-bug-tracker#413] opened 2021-07-06 00:30 UTC
**World Anvil Username**: Arcfox

**World / Campaign / RPG Character / Manuscript Title**: HollowScape: Auryl

**Feature**: Calendar BBcode

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/hollowscape3A-auryl-arcfox/a/aurylian-menology-article

**Describe the Issue**
A clear and concise description of what the issue is. When I click on the second month of my calendar, there is a massive gap between the month names and the days of the month. I can't fix it. I can even click on invisible links for the first month.

**To Reproduce**
1. Go to the month Uteus
2. Click on invisible tbody block with invisible links in the middle of the screen.
3. No need to scroll anywhere, you can clearly see my problem.

**Expected behavior**
 I want the invisible block gone. I've spent two hours of my productivity trying to find a fix. This is unacceptable.

**Screenshots**
![calendar](https://user-images.githubusercontent.com/86990955/124526121-60f79200-ddc7-11eb-8f3c-92eb0e2c47a5.PNG)

![calendar acting up](https://user-images.githubusercontent.com/86990955/124526125-62c15580-ddc7-11eb-952c-fafb3f4d91ce.PNG)

~Thanks

**Comment by iamromeo** [comment] 2021-07-06 02:47
Hey there! Please do not repost already posted bugs :) this was posted literally some hours ago. 
Duplicate of #409

**Closed by iamromeo** 2021-07-06 02:47 UTC
