### ISSUE TITLE
Calendar breaks in bootstrap 3

### ISSUE THREAD

**Issue by Naeliner** [worldanvil/worldanvil-bug-tracker#390] opened 2021-06-26 19:25 UTC
**World Anvil Username**: Naelin

**World / Campaign / RPG Character / Manuscript Title**: Symbols of Power

**Feature**: Calendars

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/symbols-of-power-naelin/a/introduction-to-sop3A-the-book-of-habits-and-beasts-document

**Describe the Issue**
There is a huge gap showing between the months' names and the days table on calendars, once you click on any months' name. Clicking on an event's name freezes the page with a fade-in effect that cannot be closed. The pop up is appearing, but it is so high in the page that it cannot be seen unless you zoom out a lot.
This is happening on Chrome and Firefox and with calendar embedded in the World Navigation Menu, a vignette, inside containers, inside spoilers, or inside columns.
I have NOT upgraded to Bootstrap 5.

**To Reproduce**
- Go to https://www.worldanvil.com/w/symbols-of-power-naelin/a/introduction-to-sop3A-the-book-of-habits-and-beasts-document and click on the button "Click here to see the calendar", or to the World Navigation Menu.
- Click on any month name. A huge gap will appear between the list of months and the month.
- Click on the month called "Sheltering" and then on the event called "Arrival of the merchant". The page will break with a black fade in.

**Expected behavior**
The gap should be just a small padding, and clicking the event name should open the description.

**Screenshots**
![Calendar fade](https://user-images.githubusercontent.com/86533873/123523598-f8a80280-d69a-11eb-9ec2-8cdb7cf50832.JPG)
![Calendar gap](https://user-images.githubusercontent.com/86533873/123523599-f9409900-d69a-11eb-814d-fda68c8d9309.JPG)

**Comment by iamromeo** [comment] 2021-06-26 20:14
This is already reported - please check the board before submitting a report 
Duplicate of https://github.com/worldanvil/worldanvil-bug-tracker/issues/387

**Closed by iamromeo** 2021-06-26 20:14 UTC

**Comment by Kordishal** [comment] 2021-06-26 20:18
Duplicate of #387
