### ISSUE TITLE
Text Wrapping on Charts

### ISSUE THREAD

**Issue by GrassyHorizon** [worldanvil/worldanvil-bug-tracker#1283] opened 2022-09-25 03:05 UTC
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: GrassyHorizon

**World / Campaign / RPG Character / Manuscript Title**: Eraterna

**Feature**: Text Tables?

**Operating System**: Windows

**Browser**: Chrome

**Device / Device Model**: Laptop, CyberpowerPC

**Related URLS** (To public & visible pages, add screenshots otherwise):  https://www.worldanvil.com/w/eraterna-grassyhorizon/a/precious-gem-values-article?preview=true

**Describe the Issue**
A clear and concise description of what the issue is.

It's not a bug, really, just something that is really bothersome for some of my pages. When I make text tables, if the table gets squished to fit the page in the best way, some of the words in the tables start wrapping and it makes the words illegible. A possible solution would be for varying text sizes, I really don't know the best way to go about it, but I do know that it can be a little annoying when trying to set up information for my players.

**To Reproduce**

**Expected behavior**
I would like to see the text get smaller so that whole words aren't split up into different lines, or the ability to choose font size so I can fix the issue without complicating your coding.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment] 2022-09-26 08:11
This isn't really something that can be solved by just using smaller text sizes always. Tables are always going to be tricky to do, because of the different screen sizes. You can control the column width to some extent by using the table options to set the width of the columns to specific percentages of the full width. Check the codex or tag reference sidebar in the article editor for more info on that.

And I believe you made a feature request on the text sizing as well so I am going to close this as it is not a bug. Its just how tables work in browsers. Use interactive tables if you want to have a fixed viewport. These then also create scrollbars when they don't fit into the space available, but always show the same way on all screen sizes.

**Closed by Kordishal** 2022-09-26 08:11 UTC
