### ISSUE TITLE
Maps can't be opened from Whiteboards

### ISSUE THREAD

**Issue by Sleeclow** [worldanvil/worldanvil-bug-tracker#1232] opened 2022-08-18 02:12 UTC
**World Anvil Username**:
 Sleeclow 
**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: Whiteboards

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

When you double click on anything on a witeboard, it opens the full article, this does not happen with maps.
**To Reproduce**
double click a map added to a Whiteboard

**Expected behavior**
For the map to open in a new tab, like all articles do when double clicked in a whiteboard.
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment] 2022-08-18 12:33
Duplicate of #1192

**Closed by Kordishal** 2022-08-18 12:33 UTC
Labels: Type: Duplicate, Type: Bug, Feature: Maps, Feature: Whiteboards
