### ISSUE TITLE
Hero's privacy "hidden" is not applied not matter what to any character

### ISSUE THREAD

**Issue by aestry** [worldanvil/worldanvil-bug-tracker#561] opened 2021-09-14 19:06 UTC
**World Anvil Username**: aestry

**RPG Character**: Theodore Clemens Brenner as well as Jane Smith and any other character I create

**Feature**: Privacy of the character I've created (the "Privacy" tab) and trying to make the character hidden from global view doesn't work

**Related URLS**: https://www.worldanvil.com/heroes/character/edit/privacy

**Describe the Issue**
I've purchased the "Epic Hero" package that specifically promised "Hero privacy". As far as I understood that feature would allow me to hide my characters from being viewed by anyone else by editing their profile through the Privacy tab and setting "Visibility" to "Hidden". However, when I do that and the system shows me the green "Your changes have been saved!" message and I navigate away from the page my character is still visible globally and when I return to the Privacy tab the "Visibility" status is reverted to "Visible". This happens not only for the existing character but also for all the new characters I create.

Before I've purchased "Epic Hero" package I was asking for help in the Discord channel on how to hide the characters, and I was directed to the "Privacy" tab, which simply didn't appear for me (as I now realize because it was a paid feature). However, when someone provided a direct link to the feature (in the form https://www.worldanvil.com/heroes/character/edit/privacy) and I clicked on it, it actually loaded the feature for my character (which perhaps is a hole in the app's security?) and I've tried to set it to "Hidden" but that didn't work. After searching around I realized that I need "Epic Hero" package for it to actually work, but even with that package it simply doesn't. 

Please note that I've tried to do this through multiple browsers on various machines (on a Mac in Safari and Firefox, on a Win 10 machine in Chrome and Firefox) all to the same results. Logging in and out and restarting also obviously didn't help.

**To Reproduce**
0. Not sure, but it's possible that in order to reproduce you will have to start from an unpaid account and try to set the feature through direct link as described above, then pay for "Epic Hero" package and only then go through the steps below.
1. Go to https://www.worldanvil.com/heroes/character/edit/privacy for any of characters under my account. 
2. Click on "Visibility" and choose "Hidden".
3. Click on "Save changes".
4. Leave the page. Then check through any other browser where you are not logged in or logged in with a different account and the character will still be visible under my profile at https://www.worldanvil.com/author/aestry in the Characters tab.

**Expected behavior**
I should be able to set "Visibility" to "Hidden" for all of my characters and the setting should be actually saved and applied and my characters should not be visible to anyone beside me (and GameMaster of the Campaign I've joined with the said character, of course).

**Comment by iamromeo** [comment] 2021-09-15 05:03
@Kordishal is there a chance you can confirm this?

**Comment by Kordishal** [comment] 2021-09-15 07:44
They've come to the Discord with this issue. I've tried troubleshooting in several ways and the problem persists to different characters. User error seems unlikely as we did step by step.

So the only thing I did not check is if there might be an issue with epic heroes, as I can't reproduce this in any way.

**Comment by aestry** [comment] 2021-09-17 13:26
Would it be possible to know how long would fixing this take by any chance? Thanks a lot in advance!

**Comment by Kordishal** [comment] 2021-09-17 17:05
It will take as long as it takes. Dimitris will most likely look at this on Tuesday.

**Comment by iamromeo** [comment] 2021-09-21 11:45
This was an issue affecting only users with Epic-hero minor memberships - now fixed

**Closed by iamromeo** 2021-09-21 11:45 UTC
Labels: Severity: Important
