### ISSUE TITLE
Pins i Created in Chronicles are visible to all players but I made them private

### ISSUE THREAD

**Issue by Kill3rh4s3** [worldanvil/worldanvil-bug-tracker#1407] opened 2023-01-08 12:25 UTC
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**killerhaseTV**:

**Terosa**:

**Chronicles**: 

**Windows**:

**Firefox**:

**PC**:

**(To public & visible pages, add screenshots otherwise):](https://www.worldanvil.com/w/terosa-killerhasetv/chronicle/die-geschichte-von-terosa-chronicle)**

**Describe the Issue**
I made a Timeline with a Map and wanted to have the zoom in effect on markers so i created some markers on my map and connected them to the events. I makde sure to set all of them Private and add the correct subscriber group for each one of them because every subscriber can just see a few specific markers and events. I than procceded to test it with one guy but he could see all markers. I didnt matter if they were private for all or private and not his subspriber group. he saw all of them

**To Reproduce**
Just create some markers and set them private. All markers are visible to everyone

**Expected behavior**
everyone will see ur markers despite them being private

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![test1](https://user-images.githubusercontent.com/122210138/211195922-fa0b4eec-e5e8-4347-adbe-6a153a574a26.PNG)
![test2](https://user-images.githubusercontent.com/122210138/211195925-99bbc8f7-e87b-4740-bcf8-c2e418c3d10d.PNG)

**Comment by RealPaulquappe** [comment] 2023-01-08 14:11
**To Reproduce**
Steps to reproduce the behavior:
1. Go to Chronicles
2. Click on Map
3. Create Map Marker
4. Go to Privacy
5. Change from "Puplic" to "Private"
6. Save Changes
7. Visit the Chronicle on another account or logged off.
8. The Marker is still visible (See error)

**Expected behavior**
A Person other than me should not be seeing the Map Marker.

**Comment by Kordishal** [comment] 2023-01-08 15:35
Duplicate of #1407.

**Comment by Kill3rh4s3** [comment] 2023-01-08 15:58
> Duplicate of #1407.

This is #1407?

**Comment by Kill3rh4s3** [comment] 2023-01-08 16:00
I found the post they said its fixed but it isnt :D

**Comment by Kordishal** [comment] 2023-01-08 16:03
Ah sorry I got confused with the discussion on Discord. Though it doesn't seem to me that the other issue is the same. It was originally reported that the privacy could not be saved. The team might have not seen that the privacy issue was also added.

**Comment by Kordishal** [comment] 2023-01-08 16:04
@Xuroth see comments on #1237

**Comment by iamromeo** [comment] 2023-01-09 03:24
closing as a duplicate

**Closed by iamromeo** 2023-01-09 03:24 UTC
Labels: Type: Bug, Feature: Chronicles

**Comment by Kill3rh4s3** [comment] 2023-01-09 16:56
It is not a duplicate!

**Comment by Kill3rh4s3** [comment] 2023-01-09 16:56
It is saved as Private but still visible to all players!

**Comment by RealPaulquappe** [comment] 2023-01-09 17:58
In the issue #1237 the problem is another than this one. #1237: Privat was not saved. 1407: it is shown even thogh privat is saved. first problem is solved, it saves the privacy setting without problems. 

therefore no dublicate, like @Kordishal statet.

**Comment by Xuroth** [comment] 2023-01-11 19:43
This is related to #1237 and the cause of both is the same. The form itself had a bug, which was resolved but the other aspect (actual validation of who can view what) was broken silently.

Leaving this issue closed, as other issue (open) references the same underlying bug.
