### ISSUE TITLE
Session report links lead to 404 page

### ISSUE THREAD

**Issue by erica447788** [worldanvil/worldanvil-bug-tracker#223] opened 2021-05-04 05:55 UTC
**World Anvil Username**: Girlhead

**World / Campaign / RPG Character / Manuscript Title**: For Alloria / For Alloria. / Toren Hardhide / Session Summaries, all of them and at least one PC link is not working

**Feature**:  Session Summaries and PC link

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/for-alloria-girlhead/a/session-13A-a-day-at-the-festival-report?preview=true?
https://www.worldanvil.com/w/for-alloria-girlhead/a/session-23A-the-eyes-report?preview=true?
https://www.worldanvil.com/w/for-alloria-girlhead/a/session-33A-pigs-and-turkeys-and-sheep2C-oh-my21-report?preview=true?
https://www.worldanvil.com/w/for-alloria-girlhead/a/session-43A-the-disappearance-of-dr-wei-report?preview=true?
https://www.worldanvil.com/w/for-alloria-girlhead/a/session-53A-bee-hind-cave-walls-report?preview=true?
https://www.worldanvil.com/w/for-alloria-girlhead/a/session-63A-how-to-bandit-report?preview=true?
https://www.worldanvil.com/w/for-alloria-girlhead/a/session-73A-defenders-of-the-sheep-report?preview=true?
https://www.worldanvil.com/w/for-alloria-girlhead/a/session-83A-if-you-can-teach-a-lizard-how-to-hunt-report?preview=true?
https://www.worldanvil.com/w/for-alloria-girlhead/a/session-93A-the-stowaway-report?preview=true?
https://www.worldanvil.com/w/for-alloria-girlhead/a/session-103A-vendaelk-report?preview=true?
https://www.worldanvil.com/w/for-alloria-girlhead/a/session-113A--the-ceremony-of-the-moon-report?preview=true?

**Issue** 
The links above lead to session reports which 404 (with the exception of the last two). The links are fixed when a link to a former player article page is removed. The article is no longer in the world because the player was expelled from the campaign,

**Expected behavior**
The links should resolve the player link to the page itself instead of going to a 404.

**Comment by Kordishal** [comment] 2021-05-04 07:34
The issue cannot easily be reproduced at the moment because just expelling or deleting a character from a campaign does not break the session reports. The session reports usually continue to work, by just resolving this link to the same page.

In this case, however, the links do not properly resolve to the page itself and instead lead to a 404 page. I cannot determine currently why this is.

@erica447788 Can you please add the @ mention text for the expelled character page?

**Comment by Kordishal** [comment] 2021-05-04 09:13
It appears that the issue is in the linked article of the player.

The character with that ID is private. Likely the article is now part of a new world and contains an issue that results in a 404. If that is the case then we would need to contact that player and they have to fix the their extended profile / world article.

Then the links should work again.

Dimitris: However, a broken link should probably not break the article it is in and instead not resolve.

**Comment by erica447788** [comment] 2021-05-06 02:28
Hello- is there anything else I can do?

**Closed** 2021-05-06 07:21 UTC
Labels: Feature: Articles & Templates, Feature: RPG Characters, Severity: Important, Type: Bug
