### ISSUE TITLE
Cannot switch map article tabs

### ISSUE THREAD

**Issue by Civviel** [worldanvil/worldanvil-bug-tracker#895] opened 2022-03-05 14:06 UTC
**World Anvil Username**: Civviels

**World / Campaign / RPG Character / Manuscript Title**: Gaea

**Feature**:  Map

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/gaea-civviels/map/c920c9e7-8a3f-45fe-b7ad-25e20d49b53f

**Describe the Issue**
When I click a marker on a map and look to the article that pops up on the left, I cannot switch the tabs up in the left corner. When I click on "species" for example, as in the screenshot below, nothing happens despite that it should be linked to a valid article that is both public and not a draft.

**To Reproduce**
1. Go to the link provided
2. Click on "Everfall", as an example
3. Look at the article to the left
4. Click on "species" (does not work as intended)

**Expected behavior**
I expected the article to shift to the "species" article.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Skjermbilde](https://user-images.githubusercontent.com/101005615/156886762-0074aeab-7283-4c1a-8ccf-700604bc6f45.PNG)

**Comment by Kordishal** [comment] 2022-03-05 15:25
Duplicate of #712

**Closed by Kordishal** 2022-03-05 15:25 UTC
Labels: Type: Duplicate, Type: Bug, Feature: Maps
