### ISSUE TITLE
Whiteboards started becoming blank after loading them recently

### ISSUE THREAD

**Issue by sondrex76** [worldanvil/worldanvil-bug-tracker#1179] opened 2022-07-22 07:39 UTC
**World Anvil Username**: sondrex76

**World**: Animora

**Feature**: Whiteboards

**Related URLS** (To public & visible pages add screenshots otherwise):
![image](https://user-images.githubusercontent.com/3610508/180387696-66fd55aa-3945-49ce-9de1-f32f25d010a4.png)

**Describe the Issue**
If I enter a whiteboard then leaves the page it seemingly becomes blank.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a whiteboard
2. Reload the whiteboard
3. It should become blank

**Expected behavior**
I should be shown my whiteboards when I enter the page, and they should not randomly become blank for no reason when I enter them

**Screenshots**
![image](https://user-images.githubusercontent.com/3610508/180388574-997b965f-3954-4cc2-a3c9-b6a619e152d5.png)

**Comment by iamromeo** [comment] 2022-07-22 16:22
Duplicate of #1176

**Closed by iamromeo** 2022-07-22 16:22 UTC

**Comment by Duranzno** [comment] 2022-07-22 16:56
Fixed!
