### ISSUE TITLE
Manuscripts are not being deleted properly

### ISSUE THREAD

**Issue by ErosOlympian** [worldanvil/worldanvil-bug-tracker#812] opened 2022-01-12 18:09 UTC
**World Anvil Username**:Eros Primordial World

**World / Campaign / RPG Character / Manuscript Title**:Eros Primordial World

**Feature**: Manuscripts

**Related URLS** (To public & visible pages add screenshots otherwise): they are not public as I was using them as a staging ground to develop ideas

**Describe the Issue**
The manuscript that i have deleted are still showing up only with their setting pages missing

**To Reproduce**
in my case simply make a manuscript and delete it. since the bug popped up every manuscript I try to delete will remain only missing their setting page

**Expected behavior**
the website will say the manuscript is deleted but the will remain without the setting mag

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by dragging & drop into this window!

![pika queen club](https://user-images.githubusercontent.com/78988288/149197063-50500d3a-2b67-4586-be11-3cc580d98a01.png)

![pika queen club keep](https://user-images.githubusercontent.com/78988288/149197353-2a78a189-6584-4698-937b-f4ee0f43dff8.png)

**Comment by iamromeo** [comment] 2022-01-13 03:05
Hello there this is a duplicate of https://github.com/worldanvil/worldanvil-bug-tracker/issues/206 
Please make sure that you check through the list of bugs before reporting ;)

**Closed by iamromeo** 2022-01-13 03:05 UTC
