### ISSUE TITLE
Articles are not visible in table of contents to subscribers

### ISSUE THREAD

**Issue by Centritan** [worldanvil/worldanvil-bug-tracker#1279] opened 2022-09-20 17:13 UTC
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Centrillion

**World / Campaign / RPG Character / Manuscript Title**:  https://www.worldanvil.com/w/dungeons-of-drakkenheim-centrillion

**Feature**:  Visibility

**Operating System**: Windows 11 Homes V. 21H2

**Browser**: Google Chrome 105.0.5195.127 (Official Build) (64-bit)

**Device / Device Model**: Asus Laptop 15 X515JA

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
Subscribers in the private world cannot see the world codex despite having the proper permissions.  Changing the article category to a book cover format makes the category visible but not the articles within it.

**To Reproduce**

**Expected behavior**
Subscribers see the World Codex on the homepage and are able to navigate to the articles.

**Screenshots**

Chat Log

[14:59] | Grandmaster Centrillion: Hi! My world   codex disappeared on the homepage for my players. It was there yesterday.   I've been writing several articles and now they're gone. I can see them as   owner, but not as subscriber. I could see them before.
-- | --
[14:59] | Liana has joined the conversation
[15:00] | Liana: Hi there! Sorry to hear you've   been having trouble with your codex. To make sure articles appear on your   homepage, edit your article, and head to the Navigation tab.   From here, check the following two boxes, and save your article:    Show in Table of Contents   Show articles under this in the Table of Contents of the World
[15:00] | Liana: File : https://tawk.link/6288f30fb0d10b6f3e735c57/a/628b3913fffa960c9f356e72/25a9eea44457d0ad39274ff5b4efffb50d3b748c/image.png
[15:01] | Liana: File : https://tawk.link/6288f30fb0d10b6f3e735c57/a/628b3913fffa960c9f356e72/faf3aa2f9d462fa1ef4c6e2778f903d1fe3e786e/image.png
[15:01] | Liana: Also ensure that your codex's   category (or categories) are visible on the homepage.
[15:02] | Liana: To do this, head to your   articles page at https://www.worldanvil.com/world/athena/, then click your   category on the left. Select Advanced Edit in the right-hand sidebar that   appears, and you'll be able to make the changes!
[15:05] | Grandmaster Centrillion: I went into   advanced edit. I see basic details, content, design, display, access. I have   "Display the Category title on the World page cover image" checked.   I don't see what else to change.
[15:07] | Grandmaster Centrillion: Ok. For some   reason, it only works if I display it as a book cover.
[15:09] | Grandmaster Centrillion: So I have a   category called Quests. If I select book view, it displays on the home page.   But if I click on it, it's empty. The articles in it have the correct   subscriber groups. I have "Show in Table of Contents" checked.
[15:10] | Liana: Have those articles in your   Quests category been published, or are they drafts? You can check this from   the Articles page, or from the right-hand sidebar when editing an article
[15:10] | Liana: Articles will need to be   published to appear on the homepage!
[15:10] | Grandmaster Centrillion: They are   published. Been working on this a few months. They were available and now   their not.
[15:11] | Grandmaster Centrillion: I have   probably 50 articles. At least most of them are published. Nothing is showing   up. I have subscriber groups listed. I added my secondary account to those   subscriber groups.
[15:12] | Liana: It sounds like you've been   pretty thorough with this, but just to confirm, have you added the subscriber   group(s) to the categories as well as the articles?
[15:14] | Grandmaster Centrillion: Yes. I made   the secondary account because my players couldn't see it. That's how I   figured to start adding the subscriber groups to the articles. It was working   before.
[15:16] | Liana: Thanks for letting me know! And   do you have any co-authors or other editors on your world, or is it just you?   Have there been any changes made to your world or articles' privacy settings   recently that you recall?
[15:16] | Grandmaster Centrillion: As a test, I   made the world public, the category public, and an article public. It is now   viewable.
[15:18] | Grandmaster Centrillion: There are no   co-authors or other editors. Just players who have no special permissions.
[15:19] | Grandmaster Centrillion: I removed the   subscriber group and readded it. Still doesn't work.
[15:20] | Liana: Ok - so it sounds like it's the   privacy settings that are causing the category to disappear on the homepage.   We've confirmed that your subscribers have been added to the world, the   category, and that article.
[15:20] | Grandmaster Centrillion: Yes.
[15:22] | Grandmaster Centrillion: The odd thing   to me is that it will only display if I select the book cover image option.
[15:22] | Liana: That's strange :thinking: If   possible, please could you add me as a subscriber in the same way you've   added the other users, and send me a link to your world? I'll then be able to   check if I can see the codex category on my end!
[15:23] | Grandmaster Centrillion: Is it   "Liana"?
[15:23] | Liana: My World Anvil username is Edenie!   :smile:
[15:24] | Grandmaster Centrillion: Done
[15:24] | Grandmaster Centrillion: Oh yeah. The   link
[15:24] | Grandmaster Centrillion: https://www.worldanvil.com/w/dungeons-of-drakkenheim-centrillion
[15:25] | Liana: This is what I see! Should I be   seeing another category under the World Codex list?
[15:25] | Liana: File : https://tawk.link/6288f30fb0d10b6f3e735c57/a/628b3913fffa960c9f356e72/990a0b8da835352fc3cc7c6d89ce846e2e302205/image.png
[15:26] | Liana: And are Quests or Player   Handbook the category you'd like me to be able to see, or is it a different   category?
[15:26] | Grandmaster Centrillion: Several. And   if you go into Quests you should see a few articles.
[15:26] | Liana: Yep, unfortuantely I'm not   seeing anything under Quests either - this is what I see:
[15:26] | Liana: File : https://tawk.link/6288f30fb0d10b6f3e735c57/a/628b3913fffa960c9f356e72/6864afe160af8fcd406d55d73f7c8e55f43a046d/image.png
[15:27] | Grandmaster Centrillion: File : https://tawk.link/6288f30fb0d10b6f3e735c57/vc/6329d4e82197f171f6fdceef/v/ff67e29ef6d859248fb8f8b7cc0431950e7eaa15/Homepage.png
[15:27] | Grandmaster Centrillion: This is what   is should look like.
[15:28] | Grandmaster Centrillion: Quests was on   the list on the left and invisible as a player until I checked the book cover   format.
[15:28] | Liana: Thanks - if possible, please   could you temporarily add me as a Co-Owner to your world? I'll have editing   access, so I can check out the subscriber groups and see if I can   troubleshoot from there.   You can do this on the Authors page: https://www.worldanvil.com/world/access/author/author/list
[15:30] | Grandmaster Centrillion: Done
[15:32] | Liana: Thanks! I've taken a look, and   it appears I've been added as a subscriber correctly. I've managed to make   Quests appear in the World Codex again by unticking the Display this Category   on the top of the World page using a Book-style cover image box. I'm just   going to take another brief look at your subscriber groups now
[15:33] | Grandmaster Centrillion: I can see it   now on my secondary account too.
[15:35] | Liana: Great, thanks for letting me   know!   I'm going to try making the world and world codex private again. I'll let you   know when I've done so. Please could you then check to see if there's any   change to what you can see in the world codex?
[15:35] | Grandmaster Centrillion: ok
[15:36] | Grandmaster Centrillion: I started   linking a whole lot of articles together using the mention system. I don't   know if that has anything to do with it. I haven't changed parent categories   or navigation.
[15:37] | Liana: Thanks, that's good to know.   I've just made the world and category private again, but unfortunately it   doesn't look like there's been a change. I added my own test account (testac)   as a subscriber and I'm getting the same empty codex as before when I view it   through that. Is there any change on your end?
[15:37] | Grandmaster Centrillion: It's all   hidden again.
[15:46] | Liana: Thanks for your patience as I   checked this out - unfortunately I can't see any other way to update this.   You might have found a bug! In this case, I recommend filing this as a bug   report, where it will go directly to our development team - they'll be able   to help you get to the bottom of this as soon as possible. You can file a bug   report here (https://github.com/worldanvil/worldanvil-bug-tracker), and full   instructions are available on the page. Please include your username, a link   to your world, and the info you shared with me above if possible.   And if the devs don't get back to you within a couple of days, please feel   free to send me an email directly at contact@worldanvil.com, and I'll follow   up with them for you!
[15:46] | Liana: I'm sorry I can't be of more   immediate help here - thank you for bearing with me as I looked into this.
[15:47] | Grandmaster Centrillion: Thank you so   much! I'll get on it.
[15:47] | Liana: you're welcome, I hope it can be   sorted soon!

**Comment by iamromeo** [comment] 2022-09-20 18:08
@Centritan are your articles also private and have the subscriber groups they should ?

**Comment by Centritan** [comment] 2022-09-20 18:09
Yes.  This was also verified by World Anvil support.

Shane

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by iamromeo** [comment] 2022-09-20 18:21
I am releasing a hotfix that should fix it - I will let you know when it is deployed so you can let me know if the issue is fixed

**Comment by Centritan** [comment] 2022-09-20 18:21
Thank you!

**Comment by Centritan** [comment] 2022-09-20 18:47
The World Codex is still blank when logging in as a subscriber.
![Test 1](https://user-images.githubusercontent.com/72288089/191339653-d5c26077-0813-43ae-bcee-03dcd10d9ba3.png)

**Comment by iamromeo** [comment] 2022-09-20 18:50
I am sorry but the above doesn''t help me to fix the issue of figure it out. 
There are too many unknowns - please send me an email to dimitris@worldanvil.com with your username and a new password so I can access your account as you and run some tests.

**Comment by Centritan** [comment] 2022-09-20 18:53
Sent.

**Comment by iamromeo** [comment] 2022-09-20 19:05
Thank you I will have a look ASAP

**Comment by iamromeo** [comment] 2022-09-20 19:09
@Centritan I can confirm the issue - and will investigate in the coming hours

**Comment by GorkamWorka** [comment] 2022-09-20 21:20
@Centritan  i just pushed a fix that i think will fix this issue can you check  ?

**Comment by Centritan** [comment] 2022-09-20 21:22
Yay!  It works now.  Thank you!

**Closed** 2022-09-21 02:31 UTC
Labels: Type: Bug, Feature: World, Severity: Critical, Status: Reproduced, Status: In Progress
