### ISSUE TITLE
Possible malfunction of view rights for Manuscripts

### ISSUE THREAD

**Issue by Mitternachtsspiel** [worldanvil/worldanvil-bug-tracker#1266] opened 2022-09-15 19:06 UTC
**World Anvil Username**: Midnightplay

**World / Campaign / RPG Character / Manuscript Title**: Operation Palingenese

**Feature**: Private chapter in Manuscript is publicly available

**Related URLS** (To public & visible pages add screenshots otherwise):
Manuscipt:
https://www.worldanvil.com/community/manuscripts/read/9170138990-midnightplay-operation-palingenese
Seemingly private chapter:
https://www.worldanvil.com/community/manuscripts/read/9170138990-midnightplay-operation-palingenese/db96499d-3c71-4122-8ffa-94b7bdb01ca4

**Describe the Issue**
I tried to partially publish a Manusscript on World Anvil while leaving certain chapters only accessible for beta readers. For those readers I created a subscriber group and that seems to work for the world itself just fine. But for a certain chapter, I just want to provide access to my subscriber group that does not work.

I followed the guidance under 5.2 in the following guide:
https://www.worldanvil.com/w/WorldAnvilCodex/a/writer-workflow

And there also appears a "Locked Content" symbol on the public manuscript page, but still anyone can access that chapter. I even tested it with different brothers and systems. (Without logging in, off course)

**To Reproduce**
Probable steps to reproduce the behavior:
1. Publish a Manuscript with multiple chapters
2. Set Manuscript to Public, so finished and published chapters can be accessed by the public
3. Publish a chapter that is set to private
4. Add Subscriber group to that chapter
5. See error (Private chapter is accessible to anyone even so it is set to private)

**Expected behavior**
I expected a chapter that is set to private and even appears with "Locked Content" to be locked content.

As far as I am aware off, I have to publish a chapter in order for it to be even remotely accessible for my followers as well as my subscribers. 

**Screenshots**
List of content in the manuscript, the currently last chapter appears with a locked symbol. But anyone can read it.
![ContentList_withLockedContent](https://user-images.githubusercontent.com/113634389/190484672-04304f34-9c24-49b2-ba5b-230ed0ae8a02.PNG)

Settings for the locked chapter:
![SettingsForLockedContent](https://user-images.githubusercontent.com/113634389/190484677-5277aa41-92fc-4bba-8932-9d375891d9ee.PNG)

Settings for the Manusscript:
![SettingsForManusscript](https://user-images.githubusercontent.com/113634389/190484678-b54cf127-cfad-4b09-8a2e-8e15eff5d2b6.PNG)

**Comment by Kordishal** [comment] 2022-09-16 06:18
duplicate of #1259

**Closed by Kordishal** 2022-09-16 06:18 UTC
Labels: Type: Duplicate, Feature: Manuscripts
