### ISSUE TITLE
Co-Authors Unable to Edit Chronicles

### ISSUE THREAD

**Issue by RiverFang13** [worldanvil/worldanvil-bug-tracker#1256] opened 2022-09-10 03:29 UTC
**World Anvil Username**: RiverFang

**World / Campaign / RPG Character / Manuscript Title**: Isekai

**Feature**: Chronicles

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/isekai/chronicle/history-of-the-southern-library-chronicle
Or any other chronicle

**Describe the Issue**
My world co-author (Shiftrex) is unable to edit the noted Chronicle when he enters the Timelines menu and clicks edit. The Chronicle appears in the public view version and will not allow him to edit the Chronicle.

I have an Inner Sanctum membership while my co-author's account is a Freeman. The world Isekai was created under my account.

**Expected behavior**
It is assumed by myself and a couple of others (this has been asked about in the help channel on Discord) that Chronicles can be edited by world co-authors. So far, this has not been the outcome.

**Comment by Kordishal** [comment] 2022-09-10 07:32
Duplicate of #1243

**Closed by Kordishal** 2022-09-10 07:32 UTC
Labels: Type: Duplicate, Feature: Chronicles
