### ISSUE TITLE
Linked articles to map markers not working

### ISSUE THREAD

**Issue by Legatus65** [worldanvil/worldanvil-bug-tracker#720] opened 2021-11-27 15:47 UTC
**World Anvil Username**: Legatus65

**World / Campaign / RPG Character / Manuscript Title**: Volkarion

**Feature**: Markers/Map editing 

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/volkarion-legatus65/map/4fde02b4-9d45-49fc-882d-2a04f0a375f7

**Describe the Issue**
A clear and concise description of what the issue is. I've linked articles to markers on the map but when I view the map and click on the markers, nothing comes up for organization, history or anything. While the option is their to view the article, nothing comes up when you click on it. In the URL it says "Article 2" or the number of the article but nothing on the page changes.

**To Reproduce**
1. Go to '...' Volkarion Map
2. Click on '....' Any Marker and in the top right click on any of the article tabs. 
3. Scroll up to '....' The URL

**Expected behavior**
A clear and concise description of what you expected to happen. I expected the article with the pictures added to come up after it was linked to a marker. Worked before but now it is not. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window
![2021-11-27](https://user-images.githubusercontent.com/95138324/143687967-65061eeb-2013-4dc8-a733-d12970e4c566.png)
!

**Comment by iamromeo** [comment] 2021-11-27 16:27
This is a duplicate of #712 
Please make sure you check the board before reporting a bug. :)

**Closed by iamromeo** 2021-11-27 16:27 UTC
