### ISSUE TITLE
Page not displaying associated text

### ISSUE THREAD

**Issue by BackworldTraveller** [worldanvil/worldanvil-bug-tracker#581] opened 2021-09-22 08:07 UTC
[Bug.docx](https://github.com/worldanvil/worldanvil-bug-tracker/files/7208852/Bug.docx)
**World Anvil Username**: BackworldTraveller

**World / Campaign / RPG Character / Manuscript Title**: Othar (Character Article)

**Feature**: Displays no details despite details having been entered and visible in preview

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/w/herrir-county-backworldtraveller/a/ohtar-person

**Describe the Issue**
Displays no details despite details having been entered and visible in preview

**To Reproduce**
Click on the above URL

**Expected behavior**
The text that has been entered should be displayed

**Screenshots**
See attached
[Bug.docx](https://github.com/worldanvil/worldanvil-bug-tracker/files/7208859/Bug.docx)

**Comment by BackworldTraveller** [comment] 2021-09-22 08:32
This seems to be affecting all articles in this world, not just this one article

**Comment by Otakurious** [comment] 2021-09-22 08:42
Don't worry its not only your world, i have the same issue at the moment. 
So while it's troublesome at least its a widespread problem and might get fixed during today!

**Comment by iamromeo** [comment] 2021-09-22 08:57
Please do not report bug again if they are already on the board 
duplicate of #580

**Closed by iamromeo** 2021-09-22 08:57 UTC

**Comment by BackworldTraveller** [comment] 2021-09-22 09:05
Thanks – but #580 is marked closed and the issue hasn’t gone away

Best Regards
David
