### ISSUE TITLE
Issue with Exporting World

### ISSUE THREAD

**Issue by EasyAIMark2** [worldanvil/worldanvil-bug-tracker#287] opened 2021-05-24 14:16 UTC
**World Anvil Username**:  Easy AI

**World / Campaign / RPG Character / Manuscript Title**:  The City of Nexus

**Feature**:  Export World Function

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I wanted to confirm the functionality of the Export World Function as I may be misunderstanding it, I am a new user at the master wordsmith tier so it may just be a personal misunderstanding of the function.  When I used the export function for a world I starting to create that I wanted to save locally it linked me to another site, after using an authentication token generated by WorldAnvil was sent an email to download a Zip file.  This zip file contained folders with JSON files and HTML links that contain raw text for articles and code, it does not include any of the descriptions I entered for article categories.
I have pasted several screenshots into this post to show various actions I took and the data I received for clarity.

**To Reproduce**
1. Go to 'World Settings > Configuration'
2. Click on 'Export World'
3. Retrieve Authentication Key and enter information
4. Download and unzip the folder from the email

**Expected behavior**
I was expecting PDFs that preserve the aesthetic settings of the created world or some sort of seed file that could be used to recreate the world. I want to confirm that this is the limit of the function and wish to know if there is a way to use this information to recreated the world in world anvil beyond simply copy-pasting data reentry.
Note that I am aware this world has few articles, it is one I just started creating and decided to use it to learn about the export functionality rather than trying it with a larger world.
Also, I may suggest a short video on how to use this function be created for future users as there are many good instructional videos created for other functions of the site and this function may require further brief explanation to rectify confusion for less tech-literate users as they may be unaware how to access JSON files or have other issues with the format.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![Issue Cap 1](https://user-images.githubusercontent.com/84722632/119360155-301c2d00-bc5f-11eb-829e-0629dc949bdc.jpg)

![Issue Cap 2](https://user-images.githubusercontent.com/84722632/119360186-35797780-bc5f-11eb-8746-9494a5553d48.jpg)

![Issue Cap 3](https://user-images.githubusercontent.com/84722632/119360203-39a59500-bc5f-11eb-8d00-beed9244a6c8.jpg)

![Issue Cap 4](https://user-images.githubusercontent.com/84722632/119360217-3d391c00-bc5f-11eb-935d-ab0d40546ab3.jpg)

![Issue Cap 5](https://user-images.githubusercontent.com/84722632/119360239-41fdd000-bc5f-11eb-8d63-8f4ddfc4f1fb.jpg)

![Issue Cap 6](https://user-images.githubusercontent.com/84722632/119360585-9d2fc280-bc5f-11eb-8078-38bed6206885.PNG)

**Comment by Kordishal** [comment] 2021-05-24 19:34
Hi! I will close this issue as this is not a bug. Everything is working as intended.

However, you raise some fair concerns so I will try to elaborate a bit on the state and future of the World Export.

1. The world export is currently not complete. It exports articles, statblock-data & manuscripts. There are quite a few things missing. This is due to the implementation just not being finished yet (the export is built on the API which is still in Alpha). The goal is absolutely to offer a full data export at some point in the future.
2. There will be no PDF export. Generating pdf from HTML & CSS is notoriously unreliable and will only lead to decent results with the simplest of articles. You can copy & paste the HTML content to Word / Google Docs or directly print to pdf from the browser.
3. The HTML file is the rendered article, while the JSON gives the full article data as it is structured in World Anvil. The JSON is intended for technical users who know how to use these files. I do not really see what non-technical users would use them for, therefore making good documentation would be impossible (and there is plenty of documentation on what JSON is).
4. The export serves currently 3 main purposes: A user wishes to reference their material in a period or place where they do not have internet. They wish to have a personal security copy of their data. They wish to leave the service and get their data out of the system. This data can be used to recreate the data in another platform either with a lot of manual labour or technical knowledge (excluding the parts that are currently missing as per point 1). There isn't currently an easy way to make this data more easily accessible as that would always simplify the data and there are potentially hundreds of target systems so keeping it in simple standard formats allows for the greatest flexibility (e.g. JSON & HTML).

That being said if you see a specific need or use case that should be covered feel free to expand on this here. However, an export that lets you preserve your worlds aesthetical presentation is neither intended nor technically feasible.

**Closed by Kordishal** 2021-05-24 19:34 UTC
