### ISSUE TITLE
Can't delete manuscript properly

### ISSUE THREAD

**Issue by NONGENTESIMUS** [worldanvil/worldanvil-bug-tracker#993] opened 2022-04-20 18:36 UTC
**World Anvil Username**:
NONGENTESIMUS

**Manuscript Title**:
System Takeover

**Describe the Issue**
I have deleted the manuscript, and it is still on my manuscript page.
As seen in the screenshot below the manuscrip basic settings are gone so I wouldn't even be able to repurpose the manuscript.

**Screenshots**
<img width="213" alt="Capture" src="https://user-images.githubusercontent.com/65397229/164299035-5032f027-ebf2-4e3f-a52b-12405d0c9120.PNG">

**Comment by iamromeo** [comment] 2022-04-21 04:22
Duplicate of https://github.com/worldanvil/worldanvil-bug-tracker/issues/206

**Closed by iamromeo** 2022-04-21 04:22 UTC
