### ISSUE TITLE
Can't move past "Choose calendar template" during Chronicle creation

### ISSUE THREAD

**Issue by catsmic** [worldanvil/worldanvil-bug-tracker#1281] opened 2022-09-23 01:13 UTC
World Anvil Username: shadowsadvancing

World / Campaign / RPG Character / Manuscript Title: Cardonia

Feature: Chronicles

Related URLS (To public & visible pages add screenshots otherwise):

Describe the Issue
Upon creating a new chronicle, it is not possible to continue through past the calendar selection. It is possible to click on one of the options, but the "next" and "back" buttons do not work. This is on Safari, and has not been tested by me on any other browser.

To Reproduce
Click "Create New Chronicle" and create the chronicle
Select "next"
Choose a calendar
Attempt to select "next" or "back" and find that nothing happens

Expected behavior
I expect to be able to properly select a calendar and move past to complete the rest of the chronicle

Screenshots
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment] 2022-09-23 03:57
Please do not open new issues, for already exist, almost to the letter exactly-named issues. 

This is a duplicate of #1271

If you are using a mobile device this is a known issue and also was never meant to support it :) - We are still investigating possible solutions

**Closed by iamromeo** 2022-09-23 03:57 UTC
