### ISSUE TITLE
Character sheets not visible from storyteller screen 

### ISSUE THREAD

**Issue by LordVertion** [worldanvil/worldanvil-bug-tracker#1004] opened 2022-04-24 19:00 UTC
**World Anvil Username**: Lord_Vertion

**World / Campaign / RPG Character / Manuscript Title**: Alephon

**Feature**: Character Sheets / Storyteller Screen

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When interacting with the storyteller screen and selecting a character, am unable to view the sheets and players tel me the also cannot see them and must go to a separate page to use it

**To Reproduce**
-Create Character Sheet D&D 5e
-Hand over sheet to player acct
-Player selects sheet for a character in campaign
-character in storyteller screen cannot see sheet

**Expected behavior**
Character sheet visible under Quick Profile, Appearance, etc.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![CaptureBUG](https://user-images.githubusercontent.com/82548505/164992172-838adc1f-3574-444a-af11-c6a0846c50c6.JPG)

**Comment by iamromeo** [comment] 2022-04-26 07:38
Duplicate of #963

**Closed by iamromeo** 2022-04-26 07:38 UTC
Labels: Type: UI / UX, Feature: Campaign
