### ISSUE TITLE
In Manuscripts the Save button on Source Code Editor does not actually save.

### ISSUE THREAD

**Issue by Nahbyr** [worldanvil/worldanvil-bug-tracker#435] opened 2021-07-15 10:15 UTC
**World Anvil Username**: Nahbyr

**World / Campaign / RPG Character / Manuscript Title**: Manuscript editor / source code editor

**Feature**:  Source code editor

**Describe the Issue**
Changing something in the source code editor and then pressing save doesn't actually save what you changed. It just updates the default editor.

**To Reproduce**
1. Manuscript scene
2. Go to View > source code
3. Type anything and press save
4. After it closes, refresh the page. Your source code edit is gone.

**Expected behavior**
I expect a save button to save. I've tested it and manually saving works. Same when you write something in the default editor after saving source code editor. I take it the auto-save happens when on a keyup in the default editor?
Should be easy to have the same code work when you close the source code editor. You literally press a button to do it. No auto-magic needed.

Thanks for the hard work!

**Comment by Nahbyr** [comment] 2021-07-15 10:58
Just found out that if you use the WYSIWYG also doesn't auto-save.

So, default editor > make something bold and then refresh. No more bold.

**Comment by Nahbyr** [comment] 2021-07-15 11:12
Also:
Select a piece of text, change the colour of that text.
Then at the end of that text, change it back to the original colour and type something.
Then change it back to the first colour and type something. Keep repeating this and then have a look at the code viewer.

You'll throw up.

`<p><span style="color: #bfedd2;">test<span style="color: #000000;">test<span style="color: #bfedd2;">test<span style="color: #000000;">test<span style="color: #bfedd2;">test</span></span></span></span></span></p>`

**Comment by iamromeo** [comment] 2021-07-15 15:53
@Xuroth can you please have a look at this and confirm if it is the case. This i the first time this is reported.

**Comment by Dresdon** [comment] 2021-07-15 17:00
> Just found out that if you use the WYSIWYG it also doesn't auto-save.
> 
> So, default editor > make something bold and then refresh. No more bold.

Similar to the artefacts added by a mouse click into the editor don't save issue.
When linking @abc brings up a list of things to select from with a mouse, click in the list to insert an item, and visually you can see it in the editor. Click the save button. Refresh, and the full item link is gone, with only @abc saved.

**Comment by iamromeo** [comment] 2021-07-16 04:56
@Dresdon just to clarify - are you just clicking a button to add styling and hten trying to save? 
That is a known fact, not issue :) all editors across the website understand a change only if you type something into them.

**Comment by Nahbyr** [comment] 2021-07-16 10:27
@iamromeo What about my issues? You just closed it on your reply to Dresdon?

**Comment by Dresdon** [comment] 2021-07-16 10:30
> @Dresdon just to clarify - are you just clicking a button to add styling and hten trying to save?
> That is a known fact, not issue :) all editors across the website understand a change only if you type something into them.

Heya @iamromeo,

I understand the work around, if you've inserted something into an editor via a mouse click, you need to do something to cause a 'key up' for it to save. And that clicking the 'Save Button' with the mouse, doesn't actually cause the mouse inserted content to save. I do find it massively visually misleading though, and the save button feels like a placebo.

**Comment by iamromeo** [comment] 2021-07-16 14:22
@Dresdon the save button actually wasn't even supposed to be there - it was mostly put there for old users that crapped themselves when they saw there was no button any longer. I will see what I can do - I just got an idea from what you said.

**Comment by iamromeo** [comment] 2021-07-16 14:42
@Nahbyr I have checked but couldn't reproduce your issue but there is a caviat. 
the WYSIWYG which is what you are using is quite the beast, and it takes time to totally load. 
There is a chance that you tried to make changes and refresh so fast that the thing was not fully loaded

Having said that, you are a grandmaster. Especially if you are using the source part **you should be using EUCLID** not PLATO. To change that go here: https://www.worldanvil.com/dashboard/user/interface 

Euclid is going to be much faster, with undo function and able ot handle the whole array of Grandmaster features. 

@Xuroth can you confirm the above assumption for me please?

**Comment by Nahbyr** [comment] 2021-07-16 15:08
@iamromeo Which issue? I posted several here (in hindsight I should've made separate reports):
1. code editor save button not saving
2. WYSIWYG not triggering auto-save
3. spans in the editor creating children spans instead of sibling spans when using WYSIWYG.

I'm already using EUCLID. I also have my pc on 24/7, the manuscript page has been open pretty much since the moment I bought Grandmaster. So I don't think it's a loading issue.

I'm genuinely curious what the issue with WYSIWYG is. I can make a short video if that helps? Then you can potentially reproduce and investigate.
Though, the WYSIWYG issues aren't breaking imo. I'm more annoyed with the code editor not saving. That has made me rage quit writing for the day, come back the day after and forgetting about why I quit the day before and hen finding out the hard way again.

**Comment by iamromeo** [comment] 2021-07-16 16:07
I am sorry bud, but you now have me utterly confused. 
First of all I only answer to the specific bug report for that report
Secondly, what manuscripts have to do with all of this?

**Comment by Nahbyr** [comment] 2021-07-16 16:43
1. Ok, so it's the one that annoys me most then. Is there a way I can help you reproduce it? Like I said, I've had the page open for much longer than it needs to fully load the WYSIWYG and I already had it switched to EUCLID. So neither of those will be the issue. I'm willing to help you get to the bottom of what's causing this.
2. I've only used the code editor on the manuscript page. I've not even touched the WYSIWYG on any other page. Could be that there's a slight difference between different pages, hence the mention of the page where I had the issue.

**Comment by iamromeo** [comment] 2021-07-17 03:32
1. Euclid does not have a **source** mode so, how is this replicable when using Euclid. Is this related to the use of the pen?

**Comment by Lyraine-Alei** [comment] 2021-07-17 03:37
I was more sharing that from my experience, Edge was the only browser that I had pen support on. My apologies, as I was detailing specifically the pen support side more than the Euclid/Plato

**Comment by Nahbyr** [comment] 2021-07-17 11:47
@iamromeo I don't know what to say. It clearly says EUCLID on the page you linked. I even tried switching it a couple times. I didn't notice any difference in the editor. Even after clearing cache. Could it be a case of it not switching on the manuscripts? Is there a way for me to check in the source code which editor is active?
![image](https://user-images.githubusercontent.com/5855327/126035853-ba9ce940-e0d8-4b1b-a442-a85e9ac8ea3c.png)
![image](https://user-images.githubusercontent.com/5855327/126035865-4a29930d-35fc-448c-831a-f91a08049be2.png)

**Comment by iamromeo** [comment] 2021-07-18 05:36
Manuscripts are not using Euclid or WYSIWYG, they are using their own editor that has nothing to do with BBcode

**Comment by Kordishal** [comment] 2021-07-18 11:43
At least the first issue I can reproduce. There is a lot of naming clashes with the editors which led to this misunderstanding.

To reproduce:

1. Open up Scene in Manuscript.
2. Click on View > Source Code
3. Type some text here
4. Press Save
5. Reload page with F5
6. Text added vanishes.

**Comment by Kordishal** [comment] 2021-07-18 11:47
@Nahbyr Please create a new issue for the span issue and detail it more.

Auto-save is currently only triggered by keyboard presses and does not trigger when the mouse is used. The team will look into changing this in the future, but there are a few things to consider.

Until then try to make a habit of adding a space and removing it before closing the tab.

**Comment by iamromeo** [comment] 2021-07-18 14:21
@Kordishal I will not be addressing any issues with the source version of the MANUSCRIPT editor -

**Closed** 2021-07-18 14:21 UTC
Labels: Feature: Manuscripts, Status: Reproduced, Type: Bug

**Comment by Nahbyr** [comment] 2021-07-18 19:49
@iamromeo Then put in another editor if it doesn't work. Why is it a different one from the rest anyway?
All I'm doing is report issues I discover.

**Comment by Kordishal** [comment] 2021-07-19 06:08
It is different because manuscripts have different requirements. There is no BBCode. Using an open source editor developed by others makes a lot of sense as a basis. At the same time the resources are limited and it is impossible to address all issues. Making it necessary to prioritize. The source mode of this editor is a rarely used feature that does its job well enough. Which is fixing errors. You can circumvent the bug by just adding a space after the save to trigger the auto-save of the editor. 

Thank you for taking the time to report issues! Being aware of these issues is always valuable, even if they will not be addressed at this time.

**Comment by Nahbyr** [comment] 2021-07-19 08:38
Thanks for the answer Kordishal. If that was the answer then I wouldn't have had to post my previous comment.
I'm a developer myself and I can understand that some things are default libraries or tools implemented for ease and that development isn't up to you, but to the original developer. Or if you can, that it may not be worth it or that there is currently no time to do it.

But just saying you're not going to fix the "MANUSCRIPT editor" sounds like you're looking down on me for writing a manuscript. I pay more than enough for the use of WA and I don't need being talked to like that.
If this had been the only bug/issue/whatever you want to call it that had received this response I could have ignored it, but it's been on all my reports. Just one-sidedly closing, with sometimes not even knowing what I'm talking about or unable to reproduce (instead of asking for more input).
I get that you are all very busy and that a lot of bug reports are being made on a daily basis (and from personal experience I know that some if not most must will be user error), but that is no excuse to look down on people. I'm also human.

I hope you all have a wonderful week. Go outside! It's perfect weather to work outside in the sun on a laptop  (if you're in Europe).

PS: I have a question about Project Homer II. I made a feature suggestion, but since English isn't my first language, I named the title wrong and I'm not receiving enough votes. But it's pretty much a must if you're working with editors/beta readers/ multiple writers on a manuscript. I can't see what's in Homer II though, so it might already be in there. Do I need to make another ticket for this question? (feature suggestion is adding annotations)

**Comment by Kordishal** [comment] 2021-07-19 12:50
You are welcome! 

Concerning your question about the Feature Suggestion: You have to wait for it to run its course. Good ideas can be picked up even if they do not reach 300 votes. Once the 20 days have elapsed Dimitris will comment on it and say whether it's already in Homer II, will be added to Homer II or has not enough support (which means you can resubmit it at some point in the future with refined wording etc. ) or it is declined (for example because it is out of scope).
