### ISSUE TITLE
Whiteboards Not Fully Functional

### ISSUE THREAD

**Issue by BanditBanzai** [worldanvil/worldanvil-bug-tracker#1371] opened 2022-11-28 05:06 UTC
**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Bandit_Banzai

**World / Campaign / RPG Character / Manuscript Title**: Artemisia Emergent

**Feature**:  Whiteboards

**Operating System**: ChromeOS  Version 107.0.5304.110 (Official Build) (32-bit)

**Browser**: Chrome

**Device / Device Model**: Lenovo CT X636F  (one of the 2-in-1 tablets with a detachable keyboard)

**Related URLS** (To public & visible pages, add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.  Text tool on bottom bar not working--reverts to cursor tool when I click within the whiteboard.  No text box or blinking cursor appears on the whiteboard.  Typing text enters none on the whiteboard.

**To Reproduce**
Steps to reproduce the behavior: 1. Go to Whiteboards
2:  Create new whiteboard.
3. Name whiteboard and set to private
4. Select text tool in bottom bar
5. Click anywhere on the whiteboard in progress
6. See the bottom bar revert to the cursor tool without leaving text box or blinking cursor
7. Type any text--none appears
8. See error

**Expected behavior**
A clear and concise description of what you expected to happen.  I was expecting a text box to be created, or to be able to place a blinking cursor and type from it.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment] 2022-11-28 07:20
Duplicate of #966

**Closed by Kordishal** 2022-11-28 07:20 UTC
