### ISSUE TITLE
Can’t type in black box (Euclid)

### ISSUE THREAD

**Issue by GalaxyWolf32** [worldanvil/worldanvil-bug-tracker#513] opened 2021-08-20 03:55 UTC
World Anvil Username: TheDoctor292

World / Campaign / RPG Character / Manuscript Title: All worlds

Feature: Euclid Editor 

Related URLS (To public & visible pages add screenshots otherwise):

Describe the Issue
I’m using the Euclid editor and sometimes when I’m writing I can’t type in the black box. I have to switch to spellcheck editor when this happens. I’m using Safari

To Reproduce

1. Go to Safari
2. Click on any article text box 
3. Scroll down to any article text box and start writing. 

Expected behavior
To type in the box at all times. 

Screenshots
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window! 

https://user-images.githubusercontent.com/89235919/130176676-35adbd83-79cf-4f57-b044-d38bd9b37178.MOV

**Comment by Kordishal** [comment] 2021-08-20 07:52
Hi, I've already written you on Discord (as SoulLink) so I am going to close this ticket. This is unlikely to be an actual issue with World Anvil and much more likely an issue on your side.

Try:

- Do the same in a private / incognito window. If the problem disappears, then the problem is caused by an extension or plugin.
- Try a different browser
- Try a different device

Should none of these resolve the issue please come back to the Discord so we can try to figure out what is going on. It sounds to me like something is interfering with the Euclid editor (which would explain why you can still write while in the spellchecker textarea)

**Closed by Kordishal** 2021-08-20 07:52 UTC
